### ISSUE TITLE
potential bug? cmake detect arch incorrectly configuring armv7 as armv5 with armv8 settings (i think)

### ISSUE THREAD

**Issue by userdocs** [zlib-ng/zlib-ng#1054]
I have some cross builds here https://github.com/userdocs/qbittorrent-nox-static/runs/4049091463

I am using http://musl.cc/#binaries cross build toolchains.

Only native `x86_64` and `aarch64-linux-musl` and `armv7r-linux-musleabihf`

`aarch64` is fine. `armv7r` works fine with `configure` but when using `cmake` i get an error 

```
cc1: error: ‘-mfloat-abi=hard’: selected processor lacks an FPU
```

But it also seem to incorrectly determine some stuff

```
-- Arch detected: 'armv5'
-- Basearch of 'armv5' has been detected as: 'arm'
```

Success with `configure` - https://github.com/userdocs/qbittorrent-nox-static/runs/4047827808?check_suite_focus=true

Failure with `cmake` - https://github.com/userdocs/qbittorrent-nox-static/runs/4047827859?check_suite_focus=true

I was hoping someone can take a look as see if it is cmake arch detection a bug in

https://github.com/zlib-ng/zlib-ng/blob/develop/cmake/detect-arch.cmake
https://github.com/zlib-ng/zlib-ng/blob/develop/cmake/detect-arch.c

**Comment by mtl1979** [comment]
We're working on a fix for ARM architecture detection for cmake... It might take a while as we need to test it on both real hardware and with cross-build toolchains...

**Comment by userdocs** [comment]
That good to know , thanks.

Can you tell me what I can patch/harcdode to make my build use the right arch settings? I could not see any cmake variable or settings to define and force v7

**Comment by mtl1979** [comment]
The whole float-abi detection code needs to be rewritten... Now it only tests if the compiler supports the flag, but not if it can actually compile using that flag... As far as I know, the test needs to include `features.h` to trigger a failure. The problem is that the header is Linux-specific and will most likely give false negatives on other operating systems.

See #1055.

**Comment by mtl1979** [comment]
To use non-default architecture, you need to use toolchain file and define `CMAKE_SYSTEM_PROCESSOR` and `CMAKE_C_COMPILER_TARGET`... There is examples in the `cmake` directory of the repository.

**Comment by userdocs** [comment]
Thanks for the update. I'm not sure I understand the full scope of the issue but I can add this: I made this github action based test to see if I had the issue using when the [Debian based cross tools](https://packages.debian.org/search?searchon=names&keywords=crossbuild-essential)

Here are 30 successful builds built on `amd46` targeting `amd46` - `arm64` - `armhf`

https://github.com/userdocs/zlib-ng-crossbuild/actions/runs/1400908617

The action made releases as well as artifacts - https://github.com/userdocs/zlib-ng-crossbuild/releases

None of them have the issue I had when using musl cross tool chain. 

This method used is identical to how I build in my script when using the musl cross toolchain so I would hope for a cmake fix for detecting the correct arch since I think it should behave the same?

If making a toolchain file solves the issue temporarily I will give it a go. Hopefully from what you said and linked a project based fix can be implemented.

**Comment by mtl1979** [comment]
@userdocs Using anything else than gcc and GNU C library will have some issues as some functions or preprocessor macros can be named differently or missing. It's not just MUSL, but also with clang and Visual C++ using Microsoft's C library. We can try detecting missing headers, but header paths that depend on command-line options are quite troublesome. 

It would be best if there was a real backwards compatible standard for C/C++ libraries, but that's not likely to happen anytime soon. Currently newer versions of standards can even remove functions that are essential for proper operation of common applications. Types like `size_t` and `long int` have had issues as long as I can remember, because there is no guarantee that 64-bit operating systems have 64-bit wide `size_t` or `long int`. For some operating systems we still need to support compiling as 32-bit.

I've worked with compiler teams for over 6 years now trying to fix them, but getting a fix implemented can take years and that's just for one issue.

**Comment by userdocs** [comment]
How comes configure picks it up correctly but cmake gets it wrong?

If it was the toolchain surely they would both get it wrong?

**Comment by mtl1979** [comment]
@userdocs cmake uses predefined macros for a lot of checks... Obviously configure doesn't use them and they are replaced with hand-written tests.

**Comment by nmoinvaz** [comment]
@userdocs can you please retest against lastest `develop` now that #1055 has been merged to see if the problem still exists?

**Comment by userdocs** [comment]
@nmoinvaz I tested the patch before it was merged and it worked, I use dev branch in my action now as well.

https://github.com/userdocs/zlib-ng-crossbuild/actions/runs/1453097879

I will close the issue now as I consider it resolved.
