### ISSUE TITLE
Add a new shim compat mode

### ISSUE THREAD

**Issue by guillemj** [zlib-ng/zlib-ng#1081]
Hi!

I just discovered this project, which is great! And have prepared Debian packages (https://git.hadrons.org/cgit/wip/debian/pkgs/zlib-ng.git/)  which I'm pondering uploading to Debian, so that I could play with a local branch for dpkg to consider switching it to use zlib-ng instead of zlib.

One immediate realization is that the compat support is stated to not be ABI compatible, so when uploading this to Debian, I'd not be even able to provide packages for that (to replace the zlib packages), as that would potentially break any other package linked against zlib. That also then means any package that would want to use zlib-ng would need to be adapted to its native API, which does not seem realistic.

Ideally, I'd like to see a new compat mode, which is just a shim for the native API and libz-ng.so. So that the shared library can coexist with the zlib one, but other projects can be transparently linked against the native zlib-ng library. This would involve providing zlib.pc, zconf.h and zlib.h referring, mapping or redirecting to the zlib-ng library and API. For the headers that could be accomplished either via macros, typedefs, or even symbol aliases I guess.

**Comment by mtl1979** [comment]
This doesn't make sense at all... Even more recent zlib versions are incompatible with older versions. Most of the changes we made to the ABI were to support 64-bit operating systems properly instead of relying on old code that was written for 16-bit processors and as such was limiting usable file sizes.

All "future" packages should be built with compatibility mode disabled to avoid any issues with packages using stock zlib. This is because zlib-ng requires properly aligned (and sometimes padded) buffers to benefit from all the new instructions.

**Comment by Dead2** [comment]
The thing is, our zlib-compat package is API compatible, but to be 100% ABI compatible the applications will need to be compiled with our headers and library. In most cases it will still work fine, such as with LD_PRELOAD trick, or using our .so file with an application compiled for another version or for stock zlib.

But there are some minor differences between stock-zlib and zlib-ng-compat, so although we have not seen reports of failures, we cannot guarantee everything will work without a recompile.
For switching to zlib-ng in a distro-wide setting, this is usually no problem, since most distros do a full rebuild between releases, exactly so that these kinds of changes gets propagated correctly.

For distro use, I would recommend first importing zlib-ng with its native API. The patches needed to use our native API are usually small (Mostly function prefixes and some changes to use modern data-types), and could be applied by the distro where deemed useful for performance.
Optionally also provide zlib-ng-compat to replace zlib, the downside to that is it removes any pressure for applications to switch over to the newer API.

**Comment by Dead2** [comment]
```
override_dh_auto_configure:
	dh_auto_configure -- \
	  -DCMAKE_LIBRARY_PATH=$(DEB_HOST_MULTIARCH) \
	  -DWITH_UNALIGNED=OFF \
	  # EOL
```
Also, why do you turn UNALIGNED access off instead of trusting cmake to know what the platform supports? That will hurt performance.

**Comment by guillemj** [comment]
> This doesn't make sense at all... Even more recent zlib versions are incompatible with older versions.

What part does not make sense? :) Also zlib is incompatible in what way, certainly not ABI, or we'd have had issues reported left and right. I don't recall API incompatibilities either TBH.

> Most of the changes we made to the ABI were to support 64-bit operating systems properly instead of relying on old code that was written for 16-bit processors and as such was limiting usable file sizes.

I'm not disputing or complaining about the API changes for the native library, I think all the work that has on in this project is great.

> All "future" packages should be built with compatibility mode disabled to avoid any issues with packages using stock zlib. This is because zlib-ng requires properly aligned (and sometimes padded) buffers to benefit from all the new instructions.

For a distribution such as Debian, that pretty much means that unless upstreams start to adopt the new API, it will not be a very good sell as potential transition to the new library. :/ But I'll expand on that on my next reply.

**Comment by mtl1979** [comment]
@guillemj That shim would basically be just the wrapper functions we already use for the compatibility mode minus all the changes that get enabled inside zlib-ng sources... It already exist, we don't need to reinvent it...

**Comment by guillemj** [comment]
> The thing is, our zlib-compat package is API compatible, but to be 100% ABI compatible the applications will need to be compiled with our headers and library. In most cases it will still work fine, such as with LD_PRELOAD trick, or using our .so file with an application compiled for another version or for stock zlib.

I can understand reluctance to give guarantees about ABI compatibility, but this then adds friction in case of trying to deploy this into distributions. And it means the zlib-compat code loses its main advantage IMO.

> But there are some minor differences between stock-zlib and zlib-ng-compat, so although we have not seen reports of failures, we cannot guarantee everything will work without a recompile.

It would be nice though if such minor differences could be controlled at build time to be able to have better compatibility for the zlib-ng-compat library though. But I was not really asking for this kind of change (at least at this time :).

> For switching to zlib-ng in a distro-wide setting, this is usually no problem, since most distros do a full rebuild between releases, exactly so that these kinds of changes gets propagated correctly.

In Debian, we never do (gratuitous) periodic mass rebuilds, because that means that then we cannot detect any ABI breakage (for example) and that then will affect partial upgrades (which we want and need to support as we do not expect users to reinstall, and the upgrade process must be solid).

> For distro use, I would recommend first importing zlib-ng with its native API.

That's what I was considering doing first, but doing just that I expect very very low adoption TBH.

> The patches needed to use our native API are usually small (Mostly function prefixes and some changes to use modern data-types),

Sure, when switching dpkg locally to test zlib-ng in addition to the build-system changes, I added something resembling the inverse of the shim I'm requesting but locally, like:

`
#ifndef WITH_LIBZ_NG
/* Compatibility symbols for zlib. */
#define zng_gzopen     gzopen
#define zng_gzread     gzread
#define zng_gzwrite    gzwrite
#define zng_gzerror    gzerror
#define zng_gzclose    gzclose
#define zng_zError     zError
#endif
`

And then switched the call sites to use the `zng_` prefix. Ideally though, I'd have liked to just include a compat `<zlib.h>` and get all the stock symbols redirected to the `zng_` ones and then when linking against -lz ending up linking with -lz-ng (this can be done f.ex. with either a symlink for the `.so` pathnames or a linker script, like glibc or libbsd do, see f.ex. https://gitlab.freedesktop.org/libbsd/libbsd/-/commit/e7cf8c5785b14fc8fbd37bb665a5f9a4f28c7888#67e794015a01b8816bd16290e5f8538236da8245_139_156 redirecting the linked library, which would not require a shim shared library to redirect symbols at run-time). So that at compile time I get all the benefits from the new API/ABI with minimal or no code modifications, being able to have both stock zlib and new zlib-ng coexist, so that packages can potentially be migrated smoothly, simply by asking package maintainers to either progressively change their Build-Depends from say `zlib1g-dev` to `libz-ng-compat-dev` (in general I expect with no further upstream code patching), or even if there would be distro-wide agreement by making that `libz-ng-compat-dev` be shipped simply as `zlib1g-dev`, and then that could be worth a targeted rebuild of all reverse build-dependencies to transparently pick up the new zlib-ng native shared library.

> and could be applied by the distro where deemed useful for performance. Optionally also provide zlib-ng-compat to replace zlib, the downside to that is it removes any pressure for applications to switch over to the newer API.

What I'm requesting is for a way that I can include the zlib-ng project in Debian and for it to be a potential alternative. If upstream does not guarantee ABI compatibility, then I'm going to be very reluctant to even ship a zlib-ng-compat shared library package that replaces the stock zlib, because you cannot have both at the same time (say one for some packages and the other for others). I of course could provide it in its own private directory for LD_PRELOADing or similar, but that will make adoption not great at all. Requiring all maintainers to patch the packages they maintain to use the native zlib-ng API is not realistic in something like Debian, where each one of them needs to be convinced individually. And we are talking about more than 1500 source packages. The stock zlib package is also used by the essential set of Debian packages which means it's always installed on any Debian system, that would mean adding an alternative that cannot be trivially migrated to is going to rise concerns or opposition.

The way Debian works, with all the above, it would add massive resistance and I expect even opposition to such a potential switch. :/

What I'm requesting (and I guess I could sit down and prepare a PR if that's deemed acceptable), is the most smooth way I see for me to propose this library as a potential candidate for either progressive and trivial adoption, or even as a potential system-wide replacement (which might require minor patching in some cases), but otherwise could be performed with a mass rebuild.

Ideally the smoothest way to provide this in Debian, that I predict would give maximum "selling points" and has the most potential for adoption either individually or distro-wide would look like this set of packages:

  * `libz-ng-dev`: Provides the headers and `.so` symlink for the native API.
  * `libz-ng2`: Provides the shared library for the native ABI.
  * `libz-ng2-compat`: Provides the zlib-ng-compat shared library that would replace the current `zlib1g` shared library (if ABI compat is somewhat guaranteed by upstream), for old or 3rd-party packages that cannot be rebuilt (for example external binary-only non-free programs or similar). This would be similar to what we do with the `libsdl1.2-compat` library.
  * `zlib1g-dev`: *If* there is distro-wide agreement to replace stock zlib with zlib-ng, this package could be provided to smooth the migration, with what I'm requesting here, with headers redirecting to the new API, and `.so` symlink or a linker script redirecting to the new native shared library, so that packages built with this would end up depending on `libz-ng2`. This is how the jpegturbo switch was done in Debian.
  * `zlib1g`: *If* there is distro-wide agreement to replace stock zlib with zlib-ng, then once everything has been rebuilt against the native zlib-ng, this could be provided (if ABI compat is somewhat guaranteed by upstream), containing the zlib-compat shared library, instead of shipping it in `libz-ng2-compat` package.

Hope that clarifies. :D

**Comment by guillemj** [comment]
> ```
> override_dh_auto_configure:
> 	dh_auto_configure -- \
> 	  -DCMAKE_LIBRARY_PATH=$(DEB_HOST_MULTIARCH) \
> 	  -DWITH_UNALIGNED=OFF \
> 	  # EOL
> ```
> 
> Also, why do you turn UNALIGNED access off instead of trusting cmake to know what the platform supports? That will hurt performance.

I do realize the build system selects this automatically. While testing this, and at least for now I wanted to go with the safest option as possible. And while I do know this is supposed to work on some architectures, I'm always uneasy with unaligned accesses. This is also what the Gentoo people are doing, see https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/zlib-ng/zlib-ng-2.0.5.ebuild#n27.

**Comment by Dead2** [comment]
@guillemj The implementation and detection for UNALIGNED_OK in zlib (that is used as a reason in the link you pointed to) is very different to the one we use. AFAIK there is no longer anything controversial about it, since we for example use vector intrinsics that support unaligned loads where needed. But if you feel you have to disable those optimizations, then go with that.

Your idea of a macro-based shim collides with your statement that applications should not need to be recompiled to use it, since macros only come into play when the application is recompiled. In any case, that would not solve anything that has not already been solved in the compat mode.

##
Staying 100% ABI compatible with upstream zlib is a goal for our compat package, but as we don't currently have any way of proving that we are, we are reluctant to claim that we are. If we are not, then that is a bug. As far as I know, all ABI-incompatibilities have been solved already.

You can check our pkgcheck CI tests, they all pass, indicating that our exported symbols are identical to stock zlib. Perhaps we could say that we are 100% ABI compatible by now, but it is hard to guarantee unless we know zlib-compat has been tested widely, such as in a distro. This is also where feedback from distros is useful, to inform us of whether they use zlib-ng and how they use it if it differs from the suggested configuration.

What we really want to discourage is dropping a custom-compiled zlib-ng compat library file into a production system, because that could then become nearly unrecoverable (due to zlib being a core library), IF there is an incompatibility with the distro one.
Switching the default zlib distro-wide should work fine, anything else is a bug or a difference in compilation parameters (certain settings add/remove parts of the API), but again, do a smoke test before rolling it out into a repo. ;)

**Comment by nmoinvaz** [comment]
Perhaps we should change the language in the README or PORTING guide to state that we _try to maintain ABI compatibility_ in ZLIB_COMPAT mode.

**Comment by nmoinvaz** [comment]
I don't think there is anything else to do on this one..
