### ISSUE TITLE
New release based on current develop HEAD?

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [zlib-ng/zlib-ng#1113]
Recently, a new release 2.0.6 was made, but AFAIU this only backported specific patches, and is pretty much behind the current develop HEAD. When is a new release upcoming, which is based on the current develop HEAD? Will that be a 2.0.x or 2.1 or 3.0 release (in the sense of semantic versioning)?

**Comment by sfc-gh-sgiesecke** [comment]
Can you provide an update on the plan for a new (minor?) release?

**Comment by mtl1979** [comment]
There is still some remaining issues we need to finish and merge before it's time for new release... Usually few days before the release @Dead2 will compile a list that includes all the changes already merged and the changes we want to merge before the new release.

I'm pretty sure the next release won't be zlib-ng 3.0.

**Comment by sfc-gh-sgiesecke** [comment]
Thanks!

Can you give a rough estimate on the timeline for that? Will it be a few more days, weeks, months?

**Comment by nmoinvaz** [comment]
I think I would like to see another release as well, so we can compile zlib-ng with our software using ClangCl.

**Comment by mtl1979** [comment]
I wouldn't personally mind having a new release before June 2022... But professionally I think there is still some questions that need to be answered and most pull requests and issues should be closed as merged/resolved.

In the end it's up to @Dead2 to propose time frame for next release and we (as in contributors) just either agree or put it on hold until we are happy with the number of fixes and changes.

**Comment by sfc-gh-sgiesecke** [comment]
> In the end it's up to @Dead2 to propose time frame for next release

@Dead2 can you give an update on the expected time frame for a new minor release?

**Comment by Dead2** [comment]
@sfc-gh-sgiesecke Stable release, as in 2.0.7 is on my TODO list.
I am unable to promise any dates, as there is quite a bit of commits to go through to consider backporting, and my health has really been quite bad lately. Luckily I finally started taking some new medication last week, so with any luck things should only get better from now on.

An alpha release of the 2.1 branch is also on my TODO, but there has been quite a bit of big changes lately so I wanted to get as much as possible of those improvements in first. There is also an API change for zlib-ng native I want to get in first, so please review #1163 if you want to.

Also, to anyone reading this, feel free to review PRs. If others have done testing, benchmarking or a code review and approved (or asked for changes) a PR, that effectively bumps that PR up the ladder and makes it more likely to land quickly.

**Comment by haampie** [comment]
Small bump :upside_down_face: 

The last release was more than two years ago

**Comment by mtl1979** [comment]
> Small bump 🙃
> 
> The last release was more than two years ago

We are ironing out last issues so the CI gives all green... There is still few fixes that need to be backported from develop branch...

**Comment by nmoinvaz** [comment]
TBH we use `develop` at work and it is pretty stable. It could be another year before a release, so why wait for a magic number?

**Comment by rhpvorderman** [comment]
@nmoinvaz because "pretty stable" is not stable enough when the user and developer are not the same person. I am pretty familiar with zlib formats and know how to debug them. I certainly don't expect this of users of my application. Rather than having the latest and greatest, I'd rather have the version that gives the least possibility of crashes. The "magic" number also ensures that lots of people will be using the exact same version. Making it more likely that any issues reveal themselves in someone elses program (who then submits a bug) rather than in my program. I just have to keep an eye on the releases here and assume that a new one will come when the issues are severe enough.

**Comment by haampie** [comment]
I appreciate the care taken in the releases :+1: alternative point of view is that 2 years of work (~350 commits) do not really get used

**Comment by mtl1979** [comment]
There was some delay due to GitHub breaking their CI and @dead2 having health issues... Not forgetting that some of us contributors also have other projects to work on...

Now we lock some CI workflows to specific operating system versions to minimize the issues if GitHub decides to upgrade their "latest" images again. We also need older OS images to test support for some instruction sets that are not "fully" supported anymore in latest images. In some cases we have to explicitly disable generating code for more recent instruction sets.

**Comment by nmoinvaz** [comment]
Closing since there have been 2.1.x releases since June.
