### ISSUE TITLE
[MSVC] zlib-ng failed due to error C2065: 'O_RDONLY': undeclared identifier

### ISSUE THREAD

**Issue by QuellaZhang** [zlib-ng/zlib-ng#1116]
The MSVC's recently changes broken zlib-ng when building ITK, the CRT does not define those macros because they are not standard C, can you help look? Our workaround: add "/D_CRT_DECLARE_NONSTDC_NAMES" to define them. The next version of VS will have this behavior.

**Repro steps:**

1. open VS 2019 x64 Tools command
2. git clone https://github.com/InsightSoftwareConsortium/ITK F:\gitP\InsightSoftwareConsortium\ITK
3. mkdir F:\gitP\InsightSoftwareConsortium\ITK\build_amd64
4. cd F:\gitP\InsightSoftwareConsortium\ITK\build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..
6. msbuild /m /p:Platform=x64 /p:Configuration=Release All_BUILD.vcxproj /t:Rebuild

**Build.log:** [build.log](https://github.com/zlib-ng/zlib-ng/files/7870039/build.log)

**Error info:**
`F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\gzlib.c(174,19): error C2065: 'O_RDONLY': undeclared identifier `
`F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\gzlib.c(175,20): error C2065: 'O_WRONLY': undeclared identifier `
`F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\gzlib.c(175,30): error C2065: 'O_CREAT': undeclared identifier `
`F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\gzlib.c(180,20): error C2065: 'O_TRUNC': undeclared identifier `
`F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\gzlib.c(181,20): error C2065: 'O_APPEND': undeclared identifier `

**Comment by mtl1979** [comment]
I tried with Visual C++ 2019 and it doesn't fail building zlib-ng either separately or with ITK.

**Comment by QuellaZhang** [comment]
Yes, this is an internal test, only reproduced on unreleased MSVC, the next version of VS will have this behavior.

**Comment by mtl1979** [comment]
That's a regression in MSVC then... We can't fix it until that specific version has been released to public... That define you mentioned has existed over 10 years and some compiler versions have had same restriction but ultimately that restriction was removed.

VS 2022 is latest publicly available version and I tested compiling zlib-ng with that too...

**Comment by QuellaZhang** [comment]
It's okay to fix it until you can reproduce it on public VS. Just to let you know what's going on here.

**Comment by nmoinvaz** [comment]
I'm not seeing that error either with `-DCMAKE_SYSTEM_VERSION=10.0.18362.0` and VS 2022.

**Comment by crackedmind** [comment]
The C++ standard reserves names that begin with an underscore in the global namespace to the implementation. Both the POSIX functions and Microsoft-specific runtime library functions are in the global namespace, but aren't part of the standard C runtime library. That's why the preferred Microsoft implementations of these functions have a leading underscore. For portability, the UCRT also supports the default names, but the Microsoft C++ compiler issues a deprecation warning when code that uses them is compiled. Only the default names are deprecated, not the functions themselves. To suppress the warning, define _CRT_NONSTDC_NO_WARNINGS before including any headers in code that uses the original POSIX names. Because the C standard doesn't allow non-standard names in header files, by default [/std:c11](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170) and [/std:c17](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170) don't expose the default names for POSIX functions, types, and macros. If these names are necessary, define _CRT_DECLARE_NONSTDC_NAMES to expose them.

From here: https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility

Windows SDK 10.0.19041 (oldest installed on my pc) already has this guard.

**Comment by nmoinvaz** [comment]
Anybody have any build logs?

**Comment by QuellaZhang** [comment]
Update. We are backing out of the change to `__STDC__` made in 17.2 Preview 2 specifically because it was breaking some projects of RWC(real world code) testing. If you want to have `__STDC__` defined, you can use the new `/Zc:__STDC__` flag. 

This decision was made recently, apologize for this. Closed this issue.
