### ISSUE TITLE
zlib-ng-git compatibility issue

### ISSUE THREAD

**Issue by ms178** [zlib-ng/zlib-ng#1350]
Hi, 

with zlib-ng-git (g8353094a) in compatiblity mode, I get the following error when trying to build proton-ge-custom when it checks out several sub-moduls,  this error does not appear if I use the 2.0.6 release of zlib-ng:

```
Submodul-Pfad 'external/Vulkan-Headers': '37164a5726f7e6113810f9557903a117498421cf' ausgecheckt
~/Downloads/proton-ge-custom/src/proton-ge-custom
~/Downloads/proton-ge-custom/src/proton-ge-custom/gst-plugins-rs ~/Downloads/proton-ge-custom/src/proton-ge-custom
    Updating crates.io index
warning: spurious network error (2 tries remaining): error reading from the zlib stream; class=Zlib (5)
warning: spurious network error (1 tries remaining): error reading from the zlib stream; class=Zlib (5)
error: failed to get `byte-slice-cast` as a dependency of package `gst-plugin-tutorial v0.8.4 (/home/marcus/Downloads/proton-ge-custom/src/proton-ge-custom/gst-plugins-rs/tutorial)`
```

**Comment by phprus** [comment]
Can you do a git bisect for your case?
Or can you provide an example of the data on which the error occurs?

**Comment by ms178** [comment]
Unfortunately I cannot be much of help debugging this further, as I am just an Arch user and use a PKGBUILD for zlib-ng-compat which is not bisect-friendly.

The easiest way to reproduce this is on Arch, trying to compile this package: https://aur.archlinux.org/packages/proton-ge-custom

`yay -a proton-ge-custom` should do that. It pulls in all the dependancies and you'll get that error as shown above once it reaches the gst-plugins-rs sub-package.

**Comment by KungFuJesus** [comment]
There was a zlib API change since the release. Are you sure that that crate isn't trying to build against zlib 1.2.11?

**Comment by ms178** [comment]
I am not sure what that crate does, but Arch is on zlib 1.2.12  for a while and that it would surprise me if that would not work there as other people got it to compile in that standard configuration. Also zlib-ng 2.0.6 poses as 1.2.11 compatible and works okay, but zlib-ng-git does not.

**Comment by KungFuJesus** [comment]
Right but often crates and other self contained build systems will pack their own specific version of a library with it.

Arch definitely uses 1.2.12 and if you are sure you're linking to the system distributed zlib, then that shouldn't be a source of an API compatibility.

It's not clear at all from your output what the error is. If switching up the headers fixes it then it seems highly suspect of an 1.2.11 v 1.2.12 issue. Can you post an actual link error?

**Comment by mtl1979** [comment]
This kind of issues should be posted downstream until there is more information about the root cause of the regression... We can't isolate issues that involve multiple third-party packages.

**Comment by ms178** [comment]
I cannot see how posting this bug report downstream would help a lot, as the issue shows up only when using the zlib-ng-git package instead of the last zlib-ng release package (or using the stock Arch zlib package). Hence this seems to be a regression coming from zlib-ng-git in my eyes. Downstream would simply suggest to not be using zlib-ng-git, I guess. This clearly needs a more in-depth analysis of someone more knowledgable than me though.

All I can do at this point, is pointing to both PKGBUILDs which I am using and ask for guidance to get this hopefully fixed before the next release.

- Proton-GE-custom: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=proton-ge-custom

- zlib-ng-git-compat: https://github.com/ms178/archpkgbuilds/blob/main/packages/zlib-ng-git/PKGBUILD

**Comment by mtl1979** [comment]
I'm not disagreeing that this is a regression... I'm just saying that package managers should lock any binary release to specific git commit hash instead of a git branch... That means downgrading one package automatically downgrades all dependencies and allows better bisecting.

Both zlib 1.2.12 and development branch of zlib-ng have known issues that will be eventually fixed... But to find any new regressions, we need binary dumps of the affected files or network/memory streams to make a test case.

**Comment by KungFuJesus** [comment]
Those pkgbuilds are not enough to go on.  Looking at the source to that crate I can't even find a direct reference to zlib, so it has to be somewhere in the dependency chain where the issue lies.

The error message looks to be more likely a runtime error reading from a compressed stream.  If so, a real stack trace with a minimal reproducer would go a long way.  FWIW, the tutorial package in that crate doesn't seem particularly important to the package being built, but it's still troubling to see the error.

**Comment by ms178** [comment]
This was probably an issue with the rust toolchain and zlib, updating the rust toolchain solved it with:

```
sudo pacman -Sy rustup
rustup default stable
rustup target add  i686-unknown-linux-gnu
```
