### ISSUE TITLE
No release containing fix for CVE-2022-37434

### ISSUE THREAD

**Issue by Kharos** [zlib-ng/zlib-ng#1446]
First of all, I am a big fan of zlib-ng. I used it as a drop-in replacement for zlib at work, the change was simple to do and brought a significant performance improvement. Deflate is an algorithm from the 1980's that is still heavily used today; having a well-performing, open, cross-platform implementation is a big boon.

zlib-ng 2.0.6 inherited [CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434) from zlib. This issue has been [fixed](https://github.com/zlib-ng/zlib-ng/issues/1323) in zlib-ng almost 7 months ago, but there was never a release containing the fix. As a developer I have to track vulnerabilities in third-party software that my software is using. This leaves me with the following options:

- convince the security team that our code is not vulnerable because we are not calling inflateGetHeader() (and hope that no other developer in my team will call this function)
- use a non-released version, e.g. stable-pre-release (and hope that it does not contain hidden bugs)
- switch back to zlib (and incur a significant performance penalty)

Any of these might possibly work, but non of these are optimal. Having an official release that includes the fix would make my life much easier, and possible the life of other persons who use zlib-ng in a commercial setting.

Actually I believe that if we want to push adoption of zlib-ng (and I would like to) then the project should get into the habit to cut a new release rather quickly after security fixes - even if the only change is a cherry-pick of the fix and an increment of the version number.

**Comment by Dead2** [comment]
We all agree that the release-model of zlib-ng has not been working out so well.
That is changing now though, we are releasing the final 2.0.x release with backports shortly, after that 2.0 will only receive important fixes.

The problem has been that 2.1 has received such a large amount of refactors of core code that has both required intensive testing and made backporting other changes harder. The 2.1 branch has mostly calmed down now, after a lot of really good refactors improving performance, stability and maintainability, and confidence in its stability is increasing.

After the upcoming 2.0 release, we will start releasing versioned pre-releases of the 2.1 branch and try to ensure that we have a good and stable 2.1 release. I will not make promises about when the next 2.1 release will come out, but when we feel it has been tested well enough, that will happen.
We will then target a more streamlined 2.1.x release model, each containing fewer changes and released more often.

I am about to add versioning to the stable pre release branch, and I hope people will make sure to run some tests on their workloads with it so that we can push it out shortly.

**Comment by nmoinvaz** [comment]
2.0.7 has been released which contains a fix for this CVE.
