### ISSUE TITLE
Premake support

### ISSUE THREAD

**Issue by CybernetHacker14** [zlib-ng/zlib-ng#1461]
I wanted to write a premake script for this library, for usage in my project.
However, the zlib files appear to be missing. It seems they are plotted as a template file for the CMake build system.

Is there a workaround for this?

**Comment by nmoinvaz** [comment]
We have a `configure` bash script that works with those same template files. If you are trying to incorporate zlib-ng into a different build system you would have to duplicate a lot of what is in `cmake` or `configure` build systems. You can also look at the `nmake` scripts as that might be a bit simpler. Other build systems beyond those 3 are not something we really provide support for.

There appears to be a CMake generator for premake [here](https://github.com/Enhex/premake-cmake). You can try it, since CMake can be used to make project files for different build systems.
