### ISSUE TITLE
building 2.1.3 fails

### ISSUE THREAD

**Issue by saschaarthur** [zlib-ng/zlib-ng#1529]
using

```
    git clone https://github.com/zlib-ng/zlib-ng && \
    cd zlib-ng && \
    git checkout 2.1.3 && \
    ./configure --prefix=$HOME --zlib-compat --native && \
    make -j 32 && \
    make install
```
on ubuntu 22.04, docker container

failing with
```

/usr/lib/gcc/x86_64-linux-gnu/11/include/tmmintrin.h:112:1: error: inlining failed in call to ‘always_inline’ ‘_mm_maddubs_epi16’: target specific option mismatch
  112 | _mm_maddubs_epi16 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~~
/root/zlib-ng/zlib-ng/arch/x86/adler32_sse42.c:65:28: note: called from here
   65 |             v_short_sum2 = _mm_maddubs_epi16(vbuf, dot2v);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:37,
                 from /root/zlib-ng/zlib-ng/arch/x86/adler32_sse42.c:13:
/usr/lib/gcc/x86_64-linux-gnu/11/include/tmmintrin.h:112:1: error: inlining failed in call to ‘always_inline’ ‘_mm_maddubs_epi16’: target specific option mismatch
```

any idea whats the problem here?

**Comment by KungFuJesus** [comment]
The issue is likely your --native combined with building with sse3 supported functions. Your compiler is not detecting sse3 support on your CPU would be my guess.

Now, it should be injecting the sse3 support flags compiling there, regardless. Does native strip those somehow?

**Comment by saschaarthur** [comment]
"Now, it should be injecting the sse3 support flags compiling there"

did you do changes?

Im not sure if native is stripping those, i can try that out.

Can i pass those flags manually?

**Comment by KungFuJesus** [comment]
You can.  In any case compiling those methods with the "native" flag to your compiler on a CPU that doesn't support them wasn't going to work, anyway.  As far as how the native flags are used with the individual compilation units, I never touched that, that's always how it's been.  

The native compilation isn't as tested because it's generally expected that most will want to build something portable machine to machine.  What does configure.log say your cflags are?

```
if test $native -eq 1; then
  avx512flag=""
  avx512vnniflag=""
  avx2flag=""
  sse2flag=""
  ssse3flag=""
  sse42flag=""
  pclmulflag=""
  vpclmulflag=""
  xsaveflag=""
  noltoflag=""
fi
```
The configure script appears to discard any flags and trust that the user is enabling and disabling supported functions.  If you want something that will run on that machine, you'll need to selectively enable the supported functions and disable the unsupported.  Personally I only tend to use the cmake buildchain for this, which appends -march=native to the build flags, not discarding the requisite ones.  You can also selectively turn off unsupported methods with CMake (it doesn't appear you can for configure).  

All this is to say the configure + make buildchain probably needs work, most of us use cmake.

**Comment by mtl1979** [comment]
This isn't a bug in zlib-ng, it's failing as expected... Dropping `--native` will make the build finish. `--native` isn't supported in containers, virtual machines or when cross-compiling. `configure` doesn't allow disabling support for all optional instruction sets as it is assumed that all modern 64-bit Intel/AMD processors support older instruction sets.

**Comment by Dead2** [comment]
@saschaarthur #1542 should fix this compilation failure.

That is not to say that compiling with --native in a docker container is a good solution, as the failing instruction set detection will cause a slower zlib-ng to be built compared to the default settings, so don't use --native.
But at least now it should no longer fail to compile.
