### ISSUE TITLE
[Feature Request] simplify the recognition of zlib-ng targets

### ISSUE THREAD

**Issue by Demonese** [zlib-ng/zlib-ng#1535]
I think it is necessary to add custom property to the cmake target of zlib-ng, such as:
```cmake
set_property(TARGET <zlib-targets> PROPERTY ZLIBNG TRUE)
```
So I can perform the following tests:
```cmake
get_target_property(IS_IT_ZLIBNG <zlib-targets> ZLIBNG)
if(${IS_IT_ZLIBNG})
    message(STATUS "THIS_IS_ZLIBNG!!!")
endif()
```
The custom property name can be determined after further discussion.

---

Without this mechanism, I have to write complex code to determine whether `zlib-ng.h` exists. Unfortunately, property `INCLUDE_DIRECTORIES` is not a simple path list, it contains cmake-generator-expressions.

**Comment by mtl1979** [comment]
No new code should assume zlib-ng behaves like zlib, so shouldn't try to compile against compatibility version of zlib-ng.

cmake already has dedicated function to detect if specific header exists. This works with both system headers and headers in the source tree, possibly located in git submodules.

**Comment by Dead2** [comment]
@Demonese If I understand correctly, `get_target_property` is only useful when zlib-ng is in a cmake subproject of your application, isn't that correct? If so, I am having a hard time understanding what this would solve, since you should already be in control of the subproject.

AFAIK, this can't be used for detection of a distro-installed zlib-ng..
If that is what you are after, you might want to look into `.pkg` files.

**Comment by Demonese** [comment]
> cmake already has dedicated function to detect if specific header exists. This works with both system headers and headers in the source tree, possibly located in git submodules.

This does work, thanks.
