### ISSUE TITLE
[Question] accellerate CRC16.

### ISSUE THREAD

**Issue by andreacampanella** [zlib-ng/zlib-ng#1547]
I have been abusing zlib-ng to use it as a framework to accellerate CRC calculations on an ARMv7 SoC, as far as I know the crc calculation is literally a byproduct of needing to make zlib fast on different platform but it's very useful for me as my small applet it's multiplatform.

The speed improvement it's drammatic, up to 10 times the old code, this team made an amazing job on this code! 

Now, I'm not a Mathematician Surgeon and as far as I understand the library only support CRC32 calculations, my software talk with another piece of hardware and I'm not in control of the way the CRC  it's calculated on the other side, so I can't just use 32 and trunk it to 16, which apparently it's not how that works. 

I was wondering how much work would it be to implement CRC16 into the library?

**Comment by mtl1979** [comment]
zlib-ng isn't supposed to be generic checksum framework, it contains only the bare minimum required to read gzip and deflate compressed files.

If we ever want to extend it to use different checksum functions (besides crc32 and adler32), it would need optimized versions for all the major architectures (x86/AMD64, ARM/AArch64 and PowerPC/Power). Optimized versions for other architectures are optional, but at least qemu should support emulating the required instructions so CI can check for errors.

**Comment by nmoinvaz** [comment]
There are different variants of both CRC16 and CRC32. I believe gzip uses CRC32-B. You can find the full lists [here](https://en.wikipedia.org/wiki/Cyclic_redundancy_check) on Wikipedia. 

If your need the Fletcher-16 checksum that it would be possible using Adler32:

![image](https://github.com/zlib-ng/zlib-ng/assets/1364432/c1d1ac81-8df6-4892-b41c-afb785ef48ad)

Otherwise the CRC-16 checksum is out of the really scope of this project. You can probably find a good implementation for your variant somewhere on GitHub.

**Comment by andreacampanella** [comment]
Thank you very much for the answers, it's all very usefull :)
