### ISSUE TITLE
README: opposite commands for `./configure`? WITH vs without.

### ISSUE THREAD

**Issue by rjzak** [zlib-ng/zlib-ng#1596]
On the [build options](https://github.com/zlib-ng/zlib-ng/#build-options) table, there are a few spots where a feature has a CMake argument like `WITH_GZFILEOP`, but the corresponding configure is shown as `--without-gzfileops`, shoudn't that be `--with-gzfileops`? Same for:

* `WITH_OPTIM`
* `WITH_NEW_STRATEGIES`

It's also on the [advanced build options](https://github.com/zlib-ng/zlib-ng/#advanced-build-options) table:

* `WITH_VPCLMULQDQ`
* `WITH_ACLE`
* `WITH_NEON`
* `WITH_ARMV6`

and a few others. In short, the CMake are uses "with" and the allegedly equal argument for the configure script says "without".

**Comment by Dead2** [comment]
The problem is that all those settings are default on, and they are set using parameters/arguments.
CMake allows both enabling and disabling the same parameter.
Configure (this is not autotools) only supports setting the opposite of the default setting.

Lets say you want to disable "OPTIM":
- With CMake you set for example `WITH_OPTIM=OFF` (various ways to set this, but command-line is one of them). 
- With configure you use `configure --without-optim`.

So changing configure to match CMake would need to change parameters to something like `--with-optim=off`, but this is not how configure traditionally is used and it would be confusing and cause problems for users, especially when configure is called using macros.

Changing CMake to match configure would result in a setting `WITHOUT_OPTIM=ON`, this is less readable and will cause confusion due to the unavoidable double negations.

Internally they both use `with` to store the variables.

**Comment by rjzak** [comment]
Maybe that could be explained? I thought it was a typo. Otherwise, the document reads like "to turn on feature X, use WITH_X=On or --without-x" which makes my head hurt. :)

**Comment by Dead2** [comment]
I'd say this is just the traditional way configure and CMake are used.
I'll admit it can be confusing if you are not used to these tools, or possibly if you want to switch back and forth between them, something you generally should not do.

The README file is already quite verbose, even listing the default settings for the parameters, and it is not right place to teach how to use the various buildsystem tools. Unfortunately I don't see any non-verbose way we would want to explain this.

**Comment by rjzak** [comment]
No worries, just thought I'd try to help.

**Comment by Dead2** [comment]
Thanks for caring :)
