### ISSUE TITLE
Level 1 compression seems to compress better than level 9 with the compat zlib

### ISSUE THREAD

**Issue by mrc0mmand** [zlib-ng/zlib-ng#1656]
Hey,

This is something that got uncovered by botan test suite in Fedora Rawhide. After the zlib -> zlib-ng transition, the botan2 test suite started failing when comparing compression levels 1 and 9 for deflate, zlib, and gzip. After [reporting it](https://github.com/randombit/botan/issues/3896) to botan upstream I did some digging around, and it looks like this is a bug in zlib-ng.

I put together a crude reproducer that shows the issue:

```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

const char* const COMPRESSION_TEST_TEXT =
   "'Twas brillig, and the slithy toves"
   "Did gyre and gimble in the wabe:"
   "All mimsy were the borogoves,"
   "And the mome raths outgrabe."

   "'Beware the Jabberwock, my son!"
   "The jaws that bite, the claws that catch!"
   "Beware the Jubjub bird, and shun"
   "The frumious Bandersnatch!'"

   "He took his vorpal sword in hand;"
   "Long time the manxome foe he sought-"
   "So rested he by the Tumtum tree"
   "And stood awhile in thought."

   "And, as in uffish thought he stood,"
   "The Jabberwock, with eyes of flame,"
   "Came whiffling through the tulgey wood,"
   "And burbled as it came!"

   "One, two! One, two! And through and through"
   "The vorpal blade went snicker-snack!"
   "He left it dead, and with its head"
   "He went galumphing back."

   "'And hast thou slain the Jabberwock?"
   "Come to my arms, my beamish boy!"
   "O frabjous day! Callooh! Callay!'"
   "He chortled in his joy."

   "'Twas brillig, and the slithy toves"
   "Did gyre and gimble in the wabe:"
   "All mimsy were the borogoves,"
   "And the mome raths outgrabe.";


int main(void) {
    Byte *out_l1, *out_l9;
    uLong out_l1_len, out_l9_len;

    out_l1_len = out_l9_len = compressBound(strlen(COMPRESSION_TEST_TEXT));
    assert(out_l1 = calloc(out_l1_len, 1));
    assert(out_l9 = calloc(out_l9_len, 1));

    assert(compress2(out_l1, &out_l1_len, COMPRESSION_TEST_TEXT, strlen(COMPRESSION_TEST_TEXT), 1) == Z_OK);
    assert(compress2(out_l9, &out_l9_len, COMPRESSION_TEST_TEXT, strlen(COMPRESSION_TEST_TEXT), 9) == Z_OK);
    printf("Input: %lu bytes\nL1 output: %lu bytes\nL9 output: %lu bytes\n",
           strlen(COMPRESSION_TEST_TEXT), out_l1_len, out_l9_len);

    assert(out_l1_len > out_l9_len);

    return 0;
}
```

On Fedora 38 (with `zlib-1.2.13-4.fc39.x86_64`):
```
$ gcc -o test -lz test.c
$ ./test 
Input: 900 bytes
L1 output: 455 bytes
L9 output: 450 bytes
```

On Fedora Rawhide (with `zlib-ng-compat-2.1.6-1.fc40.x86_64`):
```
# gcc -o test -lz test.c
# ./test 
Input: 900 bytes
L1 output: 449 bytes
L9 output: 450 bytes
test: test.c:57: main: Assertion `out_l1_len > out_l9_len' failed.
Aborted (core dumped)
```

**Comment by mrc0mmand** [comment]
Also, a note: with zlib-ng the test works as expected:
```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib-ng.h>

const char* const COMPRESSION_TEST_TEXT =
   "'Twas brillig, and the slithy toves"
   "Did gyre and gimble in the wabe:"
   "All mimsy were the borogoves,"
   "And the mome raths outgrabe."

   "'Beware the Jabberwock, my son!"
   "The jaws that bite, the claws that catch!"
   "Beware the Jubjub bird, and shun"
   "The frumious Bandersnatch!'"

   "He took his vorpal sword in hand;"
   "Long time the manxome foe he sought-"
   "So rested he by the Tumtum tree"
   "And stood awhile in thought."

   "And, as in uffish thought he stood,"
   "The Jabberwock, with eyes of flame,"
   "Came whiffling through the tulgey wood,"
   "And burbled as it came!"

   "One, two! One, two! And through and through"
   "The vorpal blade went snicker-snack!"
   "He left it dead, and with its head"
   "He went galumphing back."

   "'And hast thou slain the Jabberwock?"
   "Come to my arms, my beamish boy!"
   "O frabjous day! Callooh! Callay!'"
   "He chortled in his joy."

   "'Twas brillig, and the slithy toves"
   "Did gyre and gimble in the wabe:"
   "All mimsy were the borogoves,"
   "And the mome raths outgrabe.";


int main(void) {
    Byte *out_l1, *out_l9;
    uLong out_l1_len, out_l9_len;

    out_l1_len = out_l9_len = zng_compressBound(strlen(COMPRESSION_TEST_TEXT));
    assert(out_l1 = calloc(out_l1_len, 1));
    assert(out_l9 = calloc(out_l9_len, 1));

    assert(zng_compress2(out_l1, &out_l1_len, COMPRESSION_TEST_TEXT, strlen(COMPRESSION_TEST_TEXT), 1) == Z_OK);
    assert(zng_compress2(out_l9, &out_l9_len, COMPRESSION_TEST_TEXT, strlen(COMPRESSION_TEST_TEXT), 9) == Z_OK);
    printf("Input: %lu bytes\nL1 output: %lu bytes\nL9 output: %lu bytes\n",
           strlen(COMPRESSION_TEST_TEXT), out_l1_len, out_l9_len);

    assert(out_l1_len > out_l9_len);

    return 0;
}
```
```
# gcc -o test -lz-ng test.c
# ./test 
Input: 900 bytes
L1 output: 603 bytes
L9 output: 450 bytes
```

**Comment by Dead2** [comment]
The difference between zlib-ng-compat and zlib-ng on Fedora is that they disable our optimized algorithms when compat is on.
The optimized algorithm for level 1 is a whole lot faster, but it also compresses a lot worse, that is why Fedora avoided enabling that for the compat version since that would suddenly make every application using zlib level 1 see a potentially big increase in output size.


As you can see from your logs, our level 9 compresses the same as stock zlib level 9 does, so no problem there, and our level 1 compressed better than stock zlib level 1.
The "problem" here is that the "unoptimized" level 1 is compressing 1 byte better than level 9. It is actually not such a rare thing when it comes to stock zlib that lower levels can compress better, because they don't try to hard to find matches that are a long distance away (longer distances takes more encoding space). This is exacerbated by small files where overhead is higher.

Also, our levels 1-8 only search for a minimum of 4 bytes of matching data (since it is A LOT faster, and depending on data type it can also be beneficial for compression ratio) and will not search on once it finds a 8-byte or longer match. Our level 9 searches for a minimum of 3-bytes matches (same as stock zlib does for all levels) and tries very hard to find matches that are preferably 258-bytes long, even with a very long distance (useless for a measly 900 bytes of data).
3 byte matches have a lower potential compression gain compared to 4 bytes. In fact, due to encoding overhead many 3-byte matches will actually take more space than non-compressed, depending on distance (something that needs to be checked for and thus takes more cpu-time).

So, this is not a bug. It is more of an implementation difference. Our unoptimized level 1 algorithm compresses better than stock zlib level 1 does for this very specific data sample. That also happens to be better than our level 9, by one whole byte.


I'd say this is a flawed test, while it is better than testing the CRC32 hash of the compressed data like some projects do, it really doesn't tell you much, does it? Especially considering our optimized level 1 passes the test, because it has worse compression..
If botan insists on doing testing this way, I'd suggest comparing levels 1 and 8 instead, since they both use 4-byte matches, but even that might not give the desired results on this data. Doing the test with `news.rst` or `botan3.py` is much more likely to actually provide a good compression test.

And just to spell it out: This happens with this specific test, using short and simple ascii text. Longer and/or more complex input data will be much less likely to exhibit the same behavior.

**Comment by mrc0mmand** [comment]
Thanks a lot for the detailed description, this indeed makes sense. I'll forward this to botan upstream, so they can decide on the next steps.
