### ISSUE TITLE
Position independent code setting for ./configure script

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [zlib-ng/zlib-ng#1680]
Would it be possible to add a PIC flag (--with-pic/--without-pic) to the autotools configuration? I don't see one currently, so my workaround is to set CFLAGS.

**Comment by nmoinvaz** [comment]
You can try to set this on the command line.

https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html

**Comment by nmoinvaz** [comment]
https://stackoverflow.com/a/64552011

**Comment by AlexanderRichert-NOAA** [comment]
Thanks-- The backstory here is I'm working on updating the [Spack recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/zlib-ng/package.py), which supports both the cmake and the autotools builds. I want to add an option that will allow PIC to be enabled for either build system. I can set CFLAGS when it runs ./configure, but it would be ideal/cleaner to enable it through a ./configure script option.

**Comment by nmoinvaz** [comment]
That option is for cmake only. I don't know about configure.

**Comment by AlexanderRichert-NOAA** [comment]
Changing issue title to clarify

**Comment by mtl1979** [comment]
We do not add new features for `configure` script as it's being phased out in favor of using cmake only... It takes extra effort to support configure, cmake and NMake Makefiles as all build systems need to be kept synchronized.

Some people wanted `-fpic` for static zlib-ng library, due to need for embedding zlib-ng in another shared library, which is neither supported or encouraged... For example, neither Linux or Windows does support having same symbol in both the executable and a dependency. Either error is produced or only one of the symbols is used, which ever comes first after the current compilation unit in the command-line.

**Comment by AlexanderRichert-NOAA** [comment]
Okay understood, thanks for the info. I'll go ahead and close this.
