### ISSUE TITLE
SAST report: zlib-ng possible overrun issue in test/test_inflate_sync.cc file

### ISSUE THREAD

**Issue by ljavorsk** [zlib-ng/zlib-ng#1722]
I’m reviewing the SAST reports on the zlib-ng package and one caught my attention as it may be a true-possitive.

Here is the log from the SAST report:
Error: OVERRUN (CWE-119):
zlib-ng-2.1.6/test/test_inflate_sync.cc:28: write_constant: Write the value 0 into "c_stream.total_out". [Note: The source code implementation of the function has been overridden by a builtin model.]
zlib-ng-2.1.6/test/test_inflate_sync.cc:49: assignment: Assigning: "compr_len" = "(z_size_t)c_stream.total_out". The value of "compr_len" is now 0.
zlib-ng-2.1.6/test/test_inflate_sync.cc:53: alias: Assigning: "d_stream.next_in" = "compr". "d_stream.next_in" now points to byte 0 of "compr" (which consists of 128 bytes).
zlib-ng-2.1.6/test/test_inflate_sync.cc:66: assignment: Assigning: "d_stream.avail_in" = "(uint32_t)compr_len - 2U". The value of "d_stream.avail_in" is now 4294967294.
zlib-ng-2.1.6/test/test_inflate_sync.cc:70: overrun-buffer-arg: Overrunning buffer pointed to by "d_stream.next_in" of 128 bytes by passing it to a function which accesses it at byte offset 4294967293 using argument "d_stream.avail_in" (which evaluates to 4294967294). [Note: The source code implementation of the function has been overridden by a builtin model.]
\#   68|       EXPECT_EQ(err, Z_OK);
\#   69|   
\#   70|->     err = PREFIX(inflate)(&d_stream, Z_FINISH);
\#   71|       EXPECT_EQ(err, Z_STREAM_END);
\#   72|

As I’m not so deeply invested in the zlib code, could you please verify if this should be fixed?

**Comment by KungFuJesus** [comment]
I didn't write the test but this is clearly unsigned subtraction wrapping around.  There should probably be termination after compr_len is 0 or compr_len should be subtracted by a clamped value.

**Comment by mtl1979** [comment]
This one is easy to test as we can print real value of `compr_len` before the line where the supposed wraparound happens... In my setup, the value is `28` which shouldn't cause wraparound.

A lot of these static analysers override parts of the real code with dummy code that is supposed to be simplified version of the actual code, and that can cause false positives even on tests that have predictable input. This is mainly to avoid using "real" code that can result in a untrappable crash because the stack unwinds too far.

**Comment by ljavorsk** [comment]
Thank you for such a quick response. I know that a lot of SAST reports are false-positives (as I reviewed a lot of them), but I wasn't sure about this one, so I rather approached you, to help me address it.

@mtl1979 so you think this should also be flagged as the false-possitive?

**Comment by mtl1979** [comment]
> Thank you for such a quick response. I know that a lot of SAST reports are false-positives (as I reviewed a lot of them), but I wasn't sure about this one, so I rather approached you, to help me address it.
> 
> @mtl1979 so you think this should also be flagged as the false-possitive?

There is always small chance that different operating systems, architectures or compilers give different result, but that's why I said it's easy to verify if the issue is false positive or not. Obviously we "should" only care about the combinations we "have promised to" support. I've worked with static analysers for only few years and I already know how small number of issues are actually true positives.

**Comment by ljavorsk** [comment]
I verified the value as well and it is `28` in my case (same as yours). So I'll close it with the false positive, thank you for the collaboration
