### ISSUE TITLE
adler32_combine64 different declaration

### ISSUE THREAD

**Issue by proller** [zlib-ng/zlib-ng#198]
zutil.h:
ZEXTERN uint32_t ZEXPORT PREFIX(adler32_combine64)(uint32_t, uint32_t, z_off_t); 
adler32.c:187 :
uint32_t ZEXPORT PREFIX(adler32_combine64)(uint32_t adler1, uint32_t adler2, z_off64_t len2) {

z_off_t vs z_off64_t

**Comment by mtl1979** [comment]
There is quite a few signature mismatches that are intentional. Main reason for them is to catch unusual configurations due to differences in compilers and processor architectures. As long as there is no compiler warnings or errors, there is nothing to worry about.

**Comment by proller** [comment]
but it fail compilation if zlib-ng connected with submodule and cmake add_subdirectory
Problem in this line (and other add_definitions(...)) 
add_definitions(-DX86_64 -DX86_NOCHECK_SSE2 -DUNALIGNED_OK -DUNROLL_LESS)
- it works only inside zlib-ng dir and outside we need to set exactly same definitions like
```
target_compile_definitions (zlib PUBLIC X86_64 X86_NOCHECK_SSE2 UNALIGNED_OK UNROLL_LESS)      
target_compile_definitions (zlibstatic PUBLIC X86_64 X86_NOCHECK_SSE2 UNALIGNED_OK UNROLL_LESS)
 ```

handy solution: change all add_definitions(...) to target_compile_definitions (zlib PUBLIC ...) + target_compile_definitions (zlibstatic PUBLIC ...) +

**Comment by mtl1979** [comment]
The problem with target_compile_definitions() and few other cmake features is that they are not available in all operating systems or even Linux distributions due to not being upgraded to recent enough version of cmake yet. Some cmake features are available already in last few releases of 2.x series, but it takes years before all distributions and especially Travis CI catch up.

**Comment by mtl1979** [comment]
Some defines are also meant to be internal to zlib-ng and not to be used when compiling anything against zlib-ng.
