### ISSUE TITLE
review and merge bug fixes from madler/zlib

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#218]
We need to review the changes committed to madler/zlib from the time of the zlib-ng fork until today. Among these changes I see for example this commit that needs to be merged in zlib-ng https://github.com/madler/zlib/commit/5c44459c3b28a9bd3283aaceab7c615f8020c531

**Comment by sebpop** [comment]
I have seen that @mtl1979 has done several cherry-pick of patches from madler/zlib in the past. @mtl1979 is there any criteria based on which you selected these patches? Any reason not to use a systematic `git merge`, solve conflicts, and commit?
I am looking for some guidance on how we should proceed this time and in the future: i.e., do we want to narrow the number of differences with madler/zlib to a set of well documented changes?

**Comment by mtl1979** [comment]
@sebpop Basically I cherry-picked commits that did apply as cleanly as possible... There is some differences in type names because we deprecated some zlib-specific typedefs in favor of recently introduced standard types, or because we need our own types to support both zlib API and our own API at the same time.

Like with any external code, cherry-picking one by one makes it easier to spot oversights, and obvious errors the original author possibly did miss.

**Comment by sebpop** [comment]
Thanks for the explanations, I will cherry pick the changes that fix security bugs.
