### ISSUE TITLE
libz - Looks like we've been duplicating effort

### ISSUE THREAD

**Issue by sortie** [zlib-ng/zlib-ng#3]
Hi!

I'm Jonas. Looks like I'm not the only one that feels zlib needs a cleanup. I've been working on a cleaner and safer edition of zlib during the past year as part of my operating system. I think we should cooperate.

Our focus has been on cleaning it up thoroughly, correctness, security, proper portability, and so on. I can see we've made a lot of the same changes independently. I can see zlib-ng has done several optimizations, some of which looks interesting. We've done very little work in that area, we offer the same performance as zlib.

You can download my libz from https://sortix.org/libz/. Development is discussed in #libz on freenode, feel free to drop by. :)

**Comment by Dead2** [comment]
I had a good look through all your changesets, and it seems we have indeed made a lot of similar changes. There is also a pretty big delta due to different goals though, but I would like to pull a lot of your changes for sure. I likely will not pull all the feature-removal patches, since some of those actually make sense in embedded or statically linked setups. (disabling building gzip+crc code for example)

Too bad you started out with a mega-patch, since that makes it pretty hard to pull or audit.

At the moment I have three work-items planned:
- Finish rewriting from K&R to Ansi C (exported functions have not been touched yet)
- Rewrite to use uint types, and consider uint_fast in hotpaths where this actually helps performance (this varies a lot depending on architecture and the code itself, so needs to be done with cross-arch benchmarks and not blindly).
- Find a solution to a buffer size problem (a new exported function possibly, needs further investigation and cooperation across zlib-compatible libraries)

**Comment by mtl1979** [comment]
For all developers working for zlib-ng, it would really require making copy of sortie's libz repository and reverting all of the cosmetic changes that are unnecessary and then making clean diff against official zlib 1.2.8.
Then we could isolate the different parts that zlib-ng could benefit from and make partial diffs on separate branches. Only then we can audit the code on each branch and pull if it passes.

That's pretty big task to do in my opinion.
