### ISSUE TITLE
FYI: travis-CI adds native AArch64 support

### ISSUE THREAD

**Issue by rhenwood-arm** [zlib-ng/zlib-ng#457]
Hi,
I thought I would drop in to highlight that Travis-CI have just added native AArch64 support: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support. I recognize zlib-ng has a nice cross-compilation script to build for the supported platform on Travis-CI today but this new feature may be helpful to extend the automatic testing for the AArch64 builds.

**Comment by mtl1979** [comment]
Sometimes there is significant difference in behavior between cross-compiling and "native" compiling (on real hardware or virtual machine) due to differences in compiler implementation so I don't see anything bad in having both supported. We used to do local testing on real hardware but due to lack of time we didn't implement continuous testing.

**Comment by nmoinvaz** [comment]
Not sure if this is necessary anymore since GitHub Actions.

**Comment by rhenwood-arm** [comment]
@nmoinvaz in my reading of the GitHub actions documentation and examples it does not appear that you can specify the platform to test on today. I would happily be told otherwise though...

**Comment by nmoinvaz** [comment]
I believe you are right, it is not possible to specify the platform yet. But since the project moved from Travis CI to GitHub Actions I'm not sure if this issue is relevant anymore.

**Comment by Dead2** [comment]
Travis has been too slow and error-prone, with a very high level of false-positives due to Travis-related issues. So that made Travis loose most of its value to us.
We will add native aarch64 testing through Buildkite or Gitlab CI at some point (when I have time). The hardware to do the testing has been bought already.

**Comment by kushalkoolwal** [comment]
There is a [support forum](https://travis-ci.community/c/environments/multi-cpu-arch/96) for multi-architecture builds on Travis. Perhaps might be worthwhile posting the issue there if not already done so. Seems like many open source projects are being successfully ported over to Travis for AARCH64 CI over the last two months.

GitLab CI also has Arm 32-bit/64-bit runner support [available]( https://gitlab-runner-downloads.s3.amazonaws.com/latest/index.html
) as part of 12.6 release.

**Comment by rhenwood-arm** [comment]
I think this ticket has run it's course and can be closed.
