### ISSUE TITLE
Codecov token

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#470]
@Dead2 you need to add the codecov secret to the GitHub project. It's called `CODECOV_TOKEN`

**Comment by Dead2** [comment]
Right, I was wondering why the coverage data didn't update, but had no time to investigate. Added secret :)

**Comment by nmoinvaz** [comment]
@Dead2 for some reason `CODECOV_TOKEN` is showing in the build logs as empty. It should at least show as "***" which is what it does in my fork when set properly.

**Comment by Dead2** [comment]
@nmoinvaz I don't see how else I can set it.
It is added as a secret with name `CODECOV_TOKEN` with the one line uuid as value, and it is set on the zlib-ng repo's settings (not sure if secrets can be set on an organization-level too, but shouldn't be necessary in any case).

I see that https://github.com/codecov/codecov-action is using it differently though, not sure whether quotation marks like we have could be making trouble or not. But if it works for you, then I have no idea what could be wrong.

**Comment by Dead2** [comment]
Oh, now I see why.. The github page where you set secrets says this:
"Secrets are environment variables that are encrypted and only exposed to selected actions. Secrets are not passed to workflows that are triggered by a pull request from a fork of this repository."

So that basically means this can't work like we want it to.

**Comment by nmoinvaz** [comment]
It is possible. I am doing it in my minizip project.

**Comment by nmoinvaz** [comment]
In upload coverage action there is:

```
      env:
        # Codecov does not yet support GitHub Actions
        CODECOV_TOKEN: "${{secrets.CODECOV_TOKEN}}"
```

It is setting the environment variable `CODECOV_TOKEN` based on the secret called `CODECOV_TOKEN`.

**Comment by Dead2** [comment]
I don't think it does. I see no CI runs for `pull_request`, only for `push` in the minizip repo. And I only see runs triggered by you (since you are the only one having push access and you don't seem to run PRs).

If you have a look at https://github.com/nmoinvaz/minizip/pull/434/checks it doesn't look like you run any other checks than LGTM on PRs, only when you actually merge it into your repo.

**Comment by Dead2** [comment]
The setting controlling that is `settings -> actions -> Enable local and third party Actions for this repository`

**Comment by nmoinvaz** [comment]
Ah I see the misunderstanding. It might not be possible with PRs then unless Codecov supports GHA.
https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/4
