### ISSUE TITLE
Question: is intended to be used as drop-in replacement for desktops/servers/mobile?

### ISSUE THREAD

**Issue by okias** [zlib-ng/zlib-ng#479]
Hello. Thanks for your work on zlib-ng. I wonder, if it's intended to be able drop-in replace zlib on modern systems, where runs modern software (last 10 years developed?)

**Comment by Dead2** [comment]
zlib-ng compiled in zlib-compat mode is _supposed_ to be zlib-compatible. There may well be incompatibilities still here and there and only reports from end-users can help find and fix those.

zlib-ng is not drop-in compatible though, so you will need to re-compile the applications using zlib due to small differences in ABI. For linux, you can test with LD_PRELOAD for using zlib-ng only on a specific application, to avoid the possibility of making the while system unstable if you choose to replace zlib with zlib-ng system-wide.
