### ISSUE TITLE
longest_match questions

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#496]
I have been looking at the longest_match function. 

1. It doesn't appear that the `UNALIGNED_OK` is necessary. std2_longest_match and std3_longest_match don't do any unaligned access.
1. Why is longest_match broken into 3 separate functions? It seems like it could be a single function, with #ifdef inside for the separate comparison lengths (1 at a time, 2 at a time, or 4/8 at a time).

**Comment by mtl1979** [comment]
A lot of the code has been rewritten to avoid unaligned accesses even though x86 processors can handle them, because some compilers are not designed to emit correct instructions when some optimizations are enabled. I haven't tried to isolate each of the functions as separate files so I could compare the function contents line by line, but I suspect there is small differences in other parts of the functions than just different compare chunk size.

```UNALIGNED_OK``` can be used to both check if processor can handle unaligned loads and stores and if processor is likely little- or big-endian, as most big-endian processors don't allow unaligned accesses.

**Comment by nmoinvaz** [comment]
I was not able to find anywhere where there was unaligned access so maybe `UNALIGNED_OK` is not necessary. 

It does seem like the only difference is the compare chunk size. The difference used to be that one was for `UNALIGNED_OK` access while others were not. I think while trying to fix ASAN errors, everything might have been changed to be aligned.

https://github.com/zlib-ng/zlib-ng/commit/72214719ca8db882ab49d31872528b8b456362aa
https://github.com/zlib-ng/zlib-ng/commit/bee695a6415bbf37087be132a3c40e2e761658c0

**Comment by nmoinvaz** [comment]
Perhaps if `UNALIGNED_OK` is defined in CMakeLists.txt, it should not add `-fsanitize=alignment`.

**Comment by mtl1979** [comment]
Maybe there should be pull request to cleanup/merge the longest_match variants... Would help maintaining the code as only one version needs to be checked for improvements/issues.

**Comment by nmoinvaz** [comment]
I have abstracted out the methods of comparing 258 bytes and have done a performance testing on them:

https://gist.github.com/nmoinvaz/b70fd103c5bed104dfbcf09d5d927cfe
