### ISSUE TITLE
Warning when compiling with clang 3.7

### ISSUE THREAD

**Issue by nemequ** [zlib-ng/zlib-ng#51]
```
zlib-ng/inflate.c:1461:20: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        return -1L << 16;
               ~~~ ^
```

How about `return (long)(~(0UL)<<16);`?

**Comment by RJVB** [comment]
On Thursday October 08 2015 00:17:51 Evan Nemerson wrote:

> zlib-ng/inflate.c:1461:20: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
>        return -1L << 16;
>               ~~~ ^

Is that even true? Shifting is supposed to concern the operand's bits, not interpretation, no?

Does `return ~0L << 16` give the same warning.

Also, I'd define a macro for the concept "a machine word full of 1s" (probably exists already, no?) or if the return value here is always a 64bit mask regardless of machine architecture, I'd probably use the hex representation of -65536 (0xffffffffffff0000) or shorter, ~0xffff.

R

**Comment by nemequ** [comment]
> Is that even true?

Yes.  The [C11 spec](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) § 6.5.7 paragraph 4:

> The result of `E1 << E2` is `E1` left-shifted `E2` bit positions; vacated bits are filled with zeros. If `E1` has an unsigned type, the value of the result is `E1 × 2^E2`, reduced modulo one more than the maximum value representable in the result type. If `E1` has a signed type and nonnegative value, and `E1 × 2^E2` is representable in the result type, then that is the resulting value; **otherwise, the behavior is undefined**.

(emphasis added)

> Shifting is supposed to concern the operand's bits, not interpretation, no?

The standard specifically doesn't define the result of left shifting a negative value, meaning the implementation can do whatever it wants.  It will most likely be the same as the snippet I posted (since pretty much everyone uses two's complement), but it might not be.  Some machine might use [something else](https://en.wikipedia.org/wiki/Signed_number_representations), in which case the result could be a different value.  Basically, the current code isn't portable.

> Also, I'd define a macro for the concept "a machine word full of 1s" (probably exists already, no?)

I'm not aware of any such macro, but I don't know why you would bother.  A bitwise not isn't a particularly difficult concept.

> Does `return ~0L << 16` give the same warning.

Yes.

> or if the return value here is always a 64bit mask regardless of machine architecture, I'd probably use the hex representation of -65536 (0xffffffffffff0000) or shorter, ~0xffff.

It's not.  It's a long, which is only guaranteed to be >= 32-bit.

**Comment by RJVB** [comment]
On Thursday October 08 2015 01:21:36 Evan Nemerson wrote:

Not the first time I wonder why the standard is vague

> I'm not aware of any such macro, but I don't know why you would bother.  A bitwise not isn't a particularly difficult concept.

No (see my idea of using ~0xffff), but the total expression becomes much harder to read because of the extra brackets and the cast, when all that one should read is "return a mask with 0s in the 2 least significant bytes and 1s everywhere else" or "return a mask to zero out the 2 least significant bytes".

> > or if the return value here is always a 64bit mask regardless of machine architecture, I'd probably use the hex representation of -65536 (0xffffffffffff0000) or shorter, ~0xffff.
> 
> It's not.  It's a long, which is only guaranteed to be >= 32-bit.

The use of a capital L makes it a 64bit long, no? I've only assumed, not checked, that the function's return value is a long long or equivalent, rather than simply "long" (which I think I've only seen taking up 32 bits, even on x86_64 hosts).
If the function returns a long I'd expect some compilers to warn about lost bits.

Then again, I've always avoided ambiguity in this context.
Makes me realise I'd probably write ~0x0000ffff, just to leave no ambiguity about the more significant bytes, and to be aligned with the return type's width.

R.

**Comment by nemequ** [comment]
> Not the first time I wonder why the standard is vague

They don't want to require a specific representation for signed integers.  That seems pretty reasonable to me—it allows C to work with more hardware.

It's not really vague, it is simply that they intentionally did not define it, which allows compilers and/or hardware to define the behavior.  If you don't care about writing portable code (like if you're writing firmware) that can be quite nice.  zlib-ng, however, should be portable, which means it shouldn't depend on a specific implementation of undefined behavior.

> The use of a capital L makes it a 64bit long, no?

No.  It makes it a `long`, which the standard defines only as >= 32 bits.  If you want a `long long` (which the standard defines as >= 64 bit, not == 64 bit) you would use LL.

Okay, that's not quite right; the standard really just defines the minimum ranges (i.e., a long is capable of storing at least values between `-(2^31 - 1)` and `2^31 - 1`), but it's probably safe to assume that CHAR_BIT == 8 these days.

> Then again, I've always avoided ambiguity in this context.

~0xffff is fine if that is easier for you to parse.  That should be safe (though 0xffffffffffff0000 isn't).

**Comment by RJVB** [comment]
On Thursday October 08 2015 03:01:29 Evan Nemerson wrote:

> It's not really vague, it is simply that they intentionally did not define it, which allows compilers and/or hardware to define the behavior.

I guess one could consider a use case where you'd want to do a shift that preserves the sign bit ... but that could just as well have been an individual operation. 

> No.  It makes it a `long`, which the standard defines only as >= 32 bits.  If you want a `long long` (which the standard defines as >= 64 bit, not == 64 bit) you would use LL.

Ouch. Ahem. Of course. I really shouldn't try to be clever in public before finishing my pot of morning coffee ... :-/

> That should be safe (though 0xffffffffffff0000 isn't).

If the function is not always supposed to return a 64bit value then no, I wouldn't assume it to be safe to use a 64bit rvalue here.

R.

**Comment by Dead2** [comment]
The specifics of this goes above my head, so if anyone would care to write up a patch and create a pull request that we can then test and get consensus on, that'd be great.
Do note that I'd prefer it to be C99 compliant though.

And it really should have a short/good comment about what output is expected, and why the solution chosen is the correct one. It is evident that this line could easily be misinterpreted otherwise.

Btw: I lowe the fact that you discuss the details like this, we need more of this. :)

**Comment by Dead2** [comment]
Time to retire this issue, I think this was fixed a while ago.
