### ISSUE TITLE
Poor performance of levels 7,8,9 vs 6

### ISSUE THREAD

**Issue by neurolabusc** [zlib-ng/zlib-ng#631]
Compiling the latest commits of zlib-ng reveals [poorer performance (slower as expected, unexpectedly larger)](https://github.com/neurolabusc/zlib-bench-python) for levels 7,8,9 versus level 6. This is found for [three popular](https://blog.cloudflare.com/cloudflare-fights-cancer/) datasets used to evaluate compression. I realize that different compression strategies will do better with specific datasets. However, all these datasets (as well as neuroimaging data popular in my field) show the same behavior. In contrast, gzip shows the expected speed/compression trade off for these datasets. I note [libdeflate](https://github.com/ebiggers/libdeflate) does very well, but it does not support streaming, uses a different API and uses a huge amount of RAM for large files. Therefore, zlib-ng looks very competitive among zlib compatible libraries (and has dramatically better decompression). Data below for Ryzen 3900X Ubuntu 20.04, but similar behavior seen on my MacOS Intel laptop. 

**Silesia**
```
CompressMethod	Level	Min	Mean	Max	mb/s	%
minigzNG	6	2884	2903	2920	73	32.51
minigzNG	7	4470	4526	4601	47	33.61
minigzNG	8	6611	6707	6762	32	33.52
minigzNG	9	9012	9147	9270	24	33.51
```
![silesia_speed_size](https://user-images.githubusercontent.com/8930807/84166849-77f07700-aa43-11ea-8462-92b89712f358.png)

**Calgary**
```
CompressMethod	Level	Min	Mean	Max	mb/s	%
minigzNG	6	149	153	160	22	33.06
minigzNG	7	181	187	193	18	33.85
minigzNG	8	201	207	209	16	33.77
minigzNG	9	230	233	236	14	33.75
```
![calgary_speed_size](https://user-images.githubusercontent.com/8930807/84166912-88a0ed00-aa43-11ea-8f14-861dde29d87a.png)

**Canterbury (large)**
```
CompressMethod	Level	Min	Mean	Max	mb/s	%
minigzNG	6	429	434	439	26	28.91
minigzNG	7	782	790	809	14	28.98
minigzNG	8	996	1021	1037	11	28.96
minigzNG	9	1006	1018	1031	11	28.96
```
![cantebury_large_speed_size](https://user-images.githubusercontent.com/8930807/84166939-922a5500-aa43-11ea-9dfd-6488a62bc687.png)

**Comment by Dead2** [comment]
I am having problems reading the graphs, as I don't see where the different levels are.

But part of what you are seeing is probably that we introduced deflate_medium to replace deflate_slow in levels 4-6.
So while stock zlib uses deflate_slow in levels 4-9, we only use it for levels 7-9.

And ss far as I remember, we have not done any significant optimizations specifically for deflate_slow (and in deflate_slow don't compromise on size in order to speed things up, like we do in deflate_medium, deflate_fast and deflate_quick).

That said, I do have some deflate_slow specific optimizations in my local repo, and I was hoping to get to them this week, but that'll have to be postponed until next week most likely (Whew reviewing all those PRs takes time). My changes are minor, and give a noticeable, but not major speedup.

But to clarify, is deflate_slow doing worse compression-size wise as well?
We know we will be slightly worse than stock zlib due to not doing matching 3-byte matches, only 4+ bytes. CF does the same. This is because doing 3byte matches almost doubles the time it takes to search for matches.

**Comment by neurolabusc** [comment]
Note that the gzip that comes with Ubuntu and [minigzipMadler](https://github.com/madler/zlib) both show the expected trade off: better compression (though slower speeds) at higher compression levels. In contrast, zlib-ng is both faster AND smaller at compression level 6 versus the other levels. Here I only show compression levels 6..9 to emphasize the effect. So deflate_medium seems to be creating files with more efficient compression and in less time than deflate_slow.


**Calgary**
![calgary_speed_size](https://user-images.githubusercontent.com/8930807/84179907-a9257300-aa54-11ea-8400-c03855c72ccb.png)


```
CompressMethod	Level	Min	Mean	Max	mb/s	%
gzip	6	240	247	253	14	32.81
gzip	7	264	271	274	12	32.72
gzip	8	299	307	315	11	32.61
gzip	9	335	341	345	10	32.58
minigzipMadler	6	265	271	282	12	33.99
minigzipMadler	7	295	298	305	11	33.89
minigzipMadler	8	330	332	338	10	33.78
minigzipMadler	9	367	373	381	9	33.75
minigzNG	6	146	151	156	22	33.06
minigzNG	7	182	188	192	18	33.85
minigzNG	8	197	205	211	17	33.77
minigzNG	9	225	228	232	14	33.75
```

**Canterbury (large)**
![canterbury_large_speed_size](https://user-images.githubusercontent.com/8930807/84179936-b3e00800-aa54-11ea-827b-746989cff1d4.png)

```
gzip	6	664	672	683	17	29.19
gzip	7	1131	1155	1171	10	28.96
gzip	8	2455	2488	2521	5	28.65
gzip	9	2431	2479	2526	5	28.65
minigzipMadler	6	940	965	989	12	29.44
minigzipMadler	7	1522	1548	1578	7	29.27
minigzipMadler	8	3228	3339	3398	3	28.96
minigzipMadler	9	3239	3323	3400	3	28.96
minigzNG	6	427	433	436	26	28.91
minigzNG	7	781	795	816	14	28.98
minigzNG	8	1006	1023	1046	11	28.96
minigzNG	9	1006	1026	1053	11	28.96

```

**Silesia**
![silesia_speed_size](https://user-images.githubusercontent.com/8930807/84179949-b8a4bc00-aa54-11ea-9249-7cb1f6c9e6d8.png)

```
CompressMethod	Level	Min	Mean	Max	mb/s	%
gzip	6	6205	6269	6363	34	32.19
gzip	7	7483	7590	7691	28	32.05
gzip	8	10968	11152	11326	19	31.93
gzip	9	13763	13983	14140	15	31.91
minigzipMadler	6	7162	7268	7381	30	33.81
minigzipMadler	7	8600	8659	8775	25	33.66
minigzipMadler	8	12426	12645	12767	17	33.53
minigzipMadler	9	15529	15698	16016	14	33.51
minigzNG	6	2882	2942	3001	74	32.51
minigzNG	7	4499	4562	4634	47	33.61
minigzNG	8	6623	6738	6813	32	33.52
minigzNG	9	9179	9246	9395	23	33.51
```

**Comment by Dead2** [comment]
I wonder whether the better compression is because deflate_medium checks the next match before deciding whether to use the current one or not.
I expect that can be something that occurs more often with some kinds of data.

That might possibly also be what makes it faster (since it can skip encoding of many short matches and rather do fewer but bigger matches), but that is just a theory.

One could possibly test this by disabling the next-checking in deflate_medium and see whether it has a bigger negative effect on those datasets than it has on other datasets.

**Comment by neurolabusc** [comment]
It is curious that when [pigz is built using zlib-ng](https://github.com/neurolabusc/pigz-bench-python) it exhibits the expected behavior, of better compression with higher compression level. Here is the Silesia corpus for comparison. Note similar results at level 6 (minigzNG = 32.51%, pigzng = 32.52%), but pigz compresses smaller at higher levels. Is there some difference in the strategy between these tools?

```
CompressMethod	Level	ms	mb/s	%
gzip	6	6306	34	32.19
gzip	7	7623	28	32.05
gzip	8	11223	19	31.93
gzip	9	14104	15	31.91
pigzSystem	6	553	383	32.20
pigzSystem	7	633	335	32.06
pigzSystem	8	850	249	31.94
pigzSystem	9	1067	199	31.92
pigzng	6	380	558	32.52
pigzng	7	456	464	32.26
pigzng	8	631	336	32.18
pigzng	9	825	257	32.16
```

**Comment by nmoinvaz** [comment]
@neurolabusc are you comparing minigzip to pigz (in single threaded)?

**Comment by neurolabusc** [comment]
While increasing the threads improves the speed of pigz, it does not really influence the compression ratio. What surprises me is that pigzng continues to show better compression ratios for levels higher than 6, while minigzNG shows paradoxically poorer compression ratio at levels 7,8,9 vs 6.

```
exe	level	ms	mb/s	%	threads
pigzng	3	316	671	34.15	-p 24
pigzng	6	350	605	32.52	-p 24
pigzng	9	800	265	32.16	-p 24
pigzng	3	2223	95	34.23	-p 1
pigzng	6	3168	67	32.52	-p 1
pigzng	9	9241	23	32.16	-p 1

```

**Comment by nmoinvaz** [comment]
> Is there some difference in the strategy between these tools?

`pigz` might do better compression performance because it compresses shorter blocks.

**Comment by neurolabusc** [comment]
This effect is only seen with the `-f` argument. For gzip, libdeflate and pigz the `-f` argument forces overwrites. However, for minigzip it sets compression to Z_FILTERED. While it is unusual that Z_FILTERED is worse at these higher compression levels, this meddling in the defaults is unlikely to impact most users and use cases.  See [here](https://github.com/zlib-ng/zlib-ng/pull/677) for details. Closing the issue as this resolves the paradox for typical users.
