### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ioquatix** [zlib-ng/zlib-ng#64]
Hello.

Sorry to be a burden by my request.

I'm simply interested to know if this is a stable project and whether it can be used in production.

I'm not expecting a definitive answer, but perhaps I'm not the only one with this question.

**Comment by Dead2** [comment]
As a shared library replaceing zlib system-wide; no, zlib-ng has a few crash issues with some applications, presumably due to differences in alignment.

Statically linked or LD_PRELOAD or otherwise for a specific application it should be pretty stable, although you of course have to do your own testing before rolling this out into production systems.

Confidence-wise, I would not use zlib-ng for storage of important data at this point. For compression of html/etc to be delivered to a web-browser on-demand should not be a problem, since if you stumble upon a bug then you can just revert to stock zlib or a bugfixed zlib-ng without loosing important data.

We do need testers though, so any experiences both positive and negative would be appreciated. Currently we have no idea what applications crash with zlib-ng, and whether a recompile of that application to use zlib-ng would fix the problem.

**Comment by Adenilson** [comment]
@Dead2 any news about a release?

**Comment by ioquatix** [comment]
I'm not sure if this helps but I can explain our use case.

We are delivering images compressed using libpng. libpng uses libz for compression. We saw a significant improvement in performance using zlib-ng to generate png files. The png files are delivered to web browsers so they are not critical, but latency is very important. We haven't seen any issues or corruption, we compile the zlib-ng source directly into the application and link directly against it to produce a static binary.

**Comment by Dead2** [comment]
@Adenilson I am planning to get back to zlib-ng soon. We had some big deadlines at work before and during the summer, so time has been very short. Hoping to get the remaining issues worked out this fall.

@ioquatix That is great feedback, thank you. Real-world testing beats narrow benchmarks any day 👍

I have been doing some smaller zlib-ng work since my last commit, mostly testing and validation related, such as static analysis, valgrind runs etc. Haven't had time to test it in any applications yet unfortunately.

I am wondering whether we should rename the library before any release is done though, so it can be parallel-installed with stock zlib. Could be made an optional thing, but I haven't looked at how much needs to change to do this properly. Could be done in relation to the zlib-compat compile option perhaps, so by default we use our new name, but compiling with zlib-compat would make it use zlib-naming as well. Thoughts and PRs on this would be much appreciated.
Distros that want to switch to zlib-ng completely could choose to have a zlibng package and a zlibng-compat package, so both libraries are provided by us.

**Comment by ioquatix** [comment]
Given my limited experience...

1. zlib as maintained by Mark Addler seems to be very slow to evolve and seems to be very old code without much work to modernise it.

2. lots of libraries depend on that header and library specifically without much flexibility.

3. it's nice you can just build one library or the other, they both provide the same API, so it's very low cost to drop in, e.g. to replace compression in libpng.

I think it's good it's the same, because honestly, it makes my life much easier.

**Comment by Dead2** [comment]
@ioquatix I am not suggesting that we remove the zlib-compat features, only that we make it optional. For you, this would make no difference since you are free to compile it the way you want to anyway.
For distros, this is a big deal, since most distros will not want to change to zlib-ng completely all in one go (and they should not, unless they are a very risky cutting-edge distro). Allowing them to package and provide zlib-ng without risking breakage in any other package will make it very easy for them to accept zlib-ng into their fold. That in turn will allow both their separate packages to choose to compile against zlib-ng when/if that application has been tested to work properly with our fork. This also lets end-users/developers compile against zlib-ng without having to compile and install zlib-ng itself.

We need to think about the big picture, but we also need to make sure we don't sacrifice too much. :)

**Comment by RJVB** [comment]
On Friday August 11 2017 02:01:00 Hans Kristian Rosbach wrote:

>I am wondering whether we should rename the library before any release is done though, so it can be parallel-installed with stock zlib. Could be made an optional thing, but I haven't looked at how much needs to change to do this properly. Could be done in relation to the zlib-compat compile option perhaps, so by default we use our new name, but compiling with zlib-compat would make it use zlib-naming as well.

+++ IMVHO the zlib-compat build option makes sense only if it results in a drop-in replacement for stock zlib -- and as shown here and elsewhere there's a real interest to that. That doesn't mean though that building for a different library name makes sense only in non-compat mode:

I am more sceptical about your view on introducing zlib-ng via a different library name. You're right that this could help, but it's probably still as dependent on being a drop-in replacement. Distros like Debian and Ubuntu have a mechanism in place where users chance chose between alternative packages to provide a given feature. That makes perfect sense for a central package like zlib: just about everything and its dog depend on it. So yes, making it possible to build for a different library name also in compat mode is a good idea because it makes the endeavour less risky in the sense that it becomes much easier to switch back and forth.

It shouldn't be hard nor unheard-of to introduce a library suffix that can be specified via configure and/or cmake (ffmpeg does, for instance).

Truth be told, for me the main interest of zlib-ng is really that (if) it can be a drop-in replacement for stock zlib . New features and support for platforms zlib doesn't support are iceing on the cake (on the latter the whole compatibility issue is moot of course as long as the resulting files can be exchanged).

R.

**Comment by clopez** [comment]
FYI: Chromium developers considered switching to zlib-ng recently, but they didn't in the end mainly due to the lack of a stable release https://groups.google.com/a/chromium.org/d/msgid/blink-dev/CAKx6XHPtwuq%2B3kSMM5tMt5uZZEEnwpnYKbLRb%2B0t5L45bRDG1w%40mail.gmail.com

**Comment by Dead2** [comment]
@clopez Thanks for keeping us updated.

However, lets focus on doing it right and not rush something out just because someone wants to use it, they too will be better off if we do this right. Of course, doing things right requires time and energy, something that is unfortunately often a scarce resource in open-source. I am still hoping to release a release candidate soon, and hopefully get a proper stable out sometime this fall.

That said, I do view the hacknslash7 branch as beta quality, and most of what needs to change before release is build-system stuff and testing. The code itself seems to be in pretty good condition at this point.

**Comment by donny-dont** [comment]
Sorry for the nag @Dead2 but any updates on this? zlib-ng was brought up during the [WebKit contributors meeting](https://trac.webkit.org/wiki/October%202017%20Meeting) by the ARM folks so we've been watching this repo and are interested in giving it a go in our WebKit ports.

**Comment by mtl1979** [comment]
@donny-dont He's currently testing the renamelib branch on live system... Once that testing is finished and the code is cleaned up and ready to be merged to develop branch, we're one step closer to stable release.

**Comment by Dead2** [comment]
We are now one step closer to a stable release. We are missing one feature though; minizip, see #156 .
The renamelib branch was tested for several months in production webservers statically compiled into nginx, that means a pretty limited scope, but there were no problems detected during testing. A lot of PRs was merged today though, so that might potentially have changed. We'll need to do more wide testing to make sure no new bugs have cropped up.
I do wish we had a good test framework though, the current tests are the bare minimum "Hello world" of testing, literally.

**Comment by sebpop** [comment]
With the help of oss-fuzzers https://github.com/google/oss-fuzz/tree/master/projects/zlib-ng with more than 80% coverage I think zlib-ng now has pretty good testing in place.

@Dead2 what remains to be done to get a first stable release of zlib-ng?

A stable release would enable chromium.org and aosp to move to zlib-ng: see https://crbug.com/687631

**Comment by Dead2** [comment]
I agree. I will try to reserve time tomorrow for doing final testing and hopefully merging of a few of the remaining PRs. When that is done, I think we can create a stable branch and perhaps put out a RC.

Remaining things would probably mainly be documenting the parts where zlib-ng differs from zlib the most, and simple end-user guidance. Such as how to build, showing the configure vs cmake methods, perhaps document the most important zlib-ng specific build options. Perhaps some documentation about why zlib-ng api differs and what programs needs to do to change existing zlib-compatible code.

I do wish someone other than me could have a look over zlib-ng.h, and see whether there are more things we should change before going stable. Think things like changing datatypes to stable stdint types instead of short/int/long for example. Mainly I think we want to stay pretty close to the zlib api, while updating the api to be more strict about datatypes. It has been a while since I last looked, so I don't really remember whether there were more things I was considering to change there, but I'll try to have a look at that too tomorrow.

@sebpop Great work on the test framework and fixes these past months, it has made me a lot more confident that we are indeed ready for a stable release.

**Comment by vnair81** [comment]
@Dead2 any progress on a stable release?

**Comment by ioquatix** [comment]
We've been using it in production for several years now and it seems pretty solid!

**Comment by Dead2** [comment]
We are getting there, slowly.
We want to get a couple new function into the API, for setting and getting settings beyond the scope of normal zlib functionality.
The zlib-ng.h file still needs to get a thorough review to check whether we want/should/need to make any changes before making a stable release.
Those are the API-level blockers for making a 1.0 version.

In addition there are some minor cleanups and changes we could/should do before stable, but nothing really critical.
Documentation of differences from stock zlib is also a major task I'd like to see some progress on before a stable release.

We have also been using zlib-ng in prod for a couple years now, and have not had any real problems during runtime use (compilation issues is another matter, but that is not as critical, and is getting fixed as we find them).

**Comment by xuchunmei000** [comment]
@Dead2 any news for stable release ?
