### ISSUE TITLE
configure and cmake disagree on CPU feature checks

### ISSUE THREAD

**Issue by dankegel** [zlib-ng/zlib-ng#681]
When doing native builds, cmake actually checks whether CPU features
are present, whereas configure doesn't.

This leads to the cmake and configure builds producing different
output on the Mac CI build, which uses a Sandy Bridge processor
which supports AVX but not AVX2.

https://github.com/dankegel/zlib-ng/tree/bug638-identical-builds-tmpsssh
disables that particular runtime check and achieves identical
output from cmake and configure builds... on that one cpu.

Does CMakeLists.txt need an option for "restrict to features present on current running CPU" that
defaults to false, to match configure's behavior?

**Comment by nmoinvaz** [comment]
> Does CMakeLists.txt need an option for "restrict to features present on current running CPU" that
defaults to false, to match configure's behavior?

That sounds like the `WITH_NATIVE_INSTRUCTIONS` option, unless I am misunderstanding. Configure script also has `--native`.

I think we need to fix the issues with configure script. What was the error you were getting? As far as I know configure script does do check for CPU features but perhaps it missed one?

**Comment by nmoinvaz** [comment]
Perhaps #687 will help?

**Comment by Dead2** [comment]
Good catch.
Cmake/configure should not do runtime checking of cpu instruction support (It could potentially do that if native is enabled, but should not otherwise). It should check compiler support and leave the runtime checks to the functable code if at all possible.

We cannot expect distros or others distributing the library to compile using the latest and greatest cpus of each architecture, so it needs to be compiled with runtime checks.


With native enabled, we could potentially short-circuit functable so we automatically use the optimal function, but I don't really think that is worth the effort and added complexity. The least complicated way would probably be to not compile in functable and instead replace all calls with defines pointing directly to the function, but that is still a complex solution and is likely to matter to a very narrow selection of people.

**Comment by dankegel** [comment]
https://github.com/dankegel/zlib-ng/commit/f9fc887b813d6c0a76f38f5a2cdfbac47f138efa is probably a sufficient fix for now.
