### ISSUE TITLE
Drop-in for nginx; new Intel code

### ISSUE THREAD

**Issue by JoeUX** [zlib-ng/zlib-ng#71]
Howdy – I'd like to compile this with nginx and h2o (newer web server). So is this a file-for-file drop-in, such that I'd find out where nginx thinks zlib is and put this library there instead?

Separately, it looks like Intel has checked in some new gzip code as part of their Storage Acceleration Library, maybe an update to igzip: https://github.com/01org/isa-l/tree/master/igzip

I don't know if it's actually new, but if it is it might be of interest.

**Comment by Dead2** [comment]
It is not a file-for-file drop-in, but the whole of zlib-ng should be drop-in for zlib, both library and the whole source code project. But zlib-ng needs to be compiled with the zlib-compat flag specificed when run configure, or the appropriate define needs to be set otherwise.

Zlib-ng has some compatibility bugs, but IIRC it works good with nginx. You can use something like "LD_PRELOAD=/usr/local/lib/zlib-ng.so nginx" to make nginx use zlib-ng istead of zlib. Compiling it statically might also be an option, although I have not attempted that with nginx.

The code you refer to is unfortunately using Intels own copyright that I doubt is compatible with open-source, and certainly not zlib. So that is unfortunately not something we are very interested in =/

**Comment by JoeUX** [comment]
Thanks so much for the info. Do if static compilation isn't the default, I assume there's a glibc dependency? Do you happen to know if it works just as well with other libcs like musl? I like what I've seen of Alpine Linux, which uses musl instead of glibc, and FreeBSD, which has another libc.

I don't mind if it breaks or has glitches. I'm willing to play with it and test it on my own site. If it works, great, I lose some latency and save bandwidth. If it doesn't work, I'm no worse off, and I'll try to distill some good bug reports. I'm new to compiling C libraries on Unix-like platforms, hence the questions... I love what you're doing with zlib -- it's long overdue.

Sorry about the Intel library -- I assumed it was open source since it was on their open source website, didn't look at any licenses.

**Comment by Dead2** [comment]
I do not know from the top of my head what dependencies zlib-ng has, but it can be compiled without the gzfile functions and that should cut down on dependencies a bit. Without those there really should not be much other than malloc/free and such. But I think you need some kind of libc in any case, but I think musl should probably work fine. It might just be possible to compile it static with gcc's malloc/free and thus perhaps have no dependencies, but that is just speculation on my end.

Please keep us updated on what happens, good or bad. We are also present in #zlib-ng on the freenode irc network, a few of us are always online, but it might take a while for us to respond though.
