### ISSUE TITLE
--zlib-compat

### ISSUE THREAD

**Issue by bjne** [zlib-ng/zlib-ng#76]
Any way to make this switch the default? Helps integration.

**Comment by bjne** [comment]
ping

**Comment by Dead2** [comment]
Sorry, have been very busy at work lately.

I have been considering doing this, and I have not yet arrived at an answer. On one hand, having the file operations in zlib by default seems unnecessary, but on the other hand many people don't understand what that is, or even why they should run ./configure at all.

Now, you could just set the appropriate defines yourself.
But you really should be running configure first anyway, because otherwise you will not have most of the optimizations enabled, and then zlib-ng is just a little faster than zlib stock.

What are you trying to integrate with?

**Comment by bjne** [comment]
Sorry. I am trying to integrate with nginx, and making nginx pass the --compat flag is
more hazzle than I would like to. Except from that, it seems to build and work as should.

Maby it's just me, but "compatible" seems like a sane default.. but perhaps I dont need it?

**Comment by Dead2** [comment]
I think you misunderstand what the --zlib-compat flag does. It enables the gzfile functionality, in other words the ability to read and write gz files to and from the filesystem. Nginx is not likely to need that functionality since it will want to compress a buffer that is already in memory, and then send it over the network. So this is a good example of where you actually do not want to use --zlib-compat, since that just makes zlib-ng include code you will never use anyway.

I might be wrong though, since I have not tried compiling zlib-ng statically into nginx. But IIRC, stock nginx does not use gzfile functions. Some 3rd party modules might possibly, though I can't imagine why.

But if you still want it, you can add the equivalent defines to your cflags when compiling nginx. In fact you should run ./configure to see what define flags it adds and then add those to nginx anyways, otherwise you are running zlib-ng without most of its optimizations.

Also you probably need the patch mentioned here:
https://forum.nginx.org/read.php?2,252113,252133#msg-252133
Nginx cheats by not running the proper zlib initialization, so that workaround makes it at least behave a little better.
