### ISSUE TITLE
SSE-optimized adler32

### ISSUE THREAD

**Issue by mtl1979** [zlib-ng/zlib-ng#91]
Work on SSE-optimized adler32 was started years ago, but the code was never finished or cleaned up because of limited hardware support... As we already have started work on NEON-optimized adler32 function for ARM/AARCH64 and progress on that is steady, we should consider what will be the minimum SSE version we should require for SSE-optimized adler32 function and should we make several versions that take advantage of instructions added after the baseline instruction set we decide to require.

The main issue that I can think of is that some of the intrinsics only work on 32-bit processors and are not supported on x86_64/AMD64 processors. This might require writing part of the optimized code using integer registers instead of MMX/SSE registers.

**Comment by RJVB** [comment]
On Saturday February 25 2017 00:33:03 Mika Lindqvist wrote:

>The main issue that I can think of is that some of the intrinsics only work on 32-bit processors and are not supported on x86_64/AMD64 processors. This might require writing part of the optimized code using integer registers instead of MMX/SSE registers.

How is that an issue? Code built for 64 bit won't run on 32 bit CPUs, and 32 bit code will run sub-optimally on 64 bit CPUs. So what's wrong with conditional code to achieve optimal performance when running natively on either architecture (= on 32 bit)? Lots of conditional code isn't very nice to maintain but should be justifiable if it improves your ultimate goal significantly (performance here).

**Comment by mtl1979** [comment]
@RJVB It's an issue if code built for 32-bit processors doesn't run or compile on 64-bit processors. I know there is alternatives for such intrinsics, but I don't know if there is performance penalty and if there is, how significant it is. Workarounds can also cause issues when we have to support other compilers than gcc and clang (including Microsoft Visual C/C++)

The original SSE2/SSSE3-optimized adler32 functions were written in inline gcc assembly with no intrinsic functions at all. This means it didn't work on other compilers and even with gcc caused instruction stalls on earlier processors and that did equal to bad performance.

**Comment by RJVB** [comment]
It wouldn't shock me if an application or library that aims to maximise performance runs only on the architecture it was built for. As I said, the 64 bit version already doesn't run on 32 bit CPUs for obvious reasons, it would only be fair if the reverse were true too ;)

You might even end up with separate implementation files for different architectures (or even compilers) if that makes maintenance easier.

**Comment by mtl1979** [comment]
@RJVB We already have some files that only work with Visual C/C++. I opened this issue because only few contributors are on the #zlib-ng IRC channel on FreeNode and keeping the discussion available to everyone makes following it easier.

**Comment by JoeUX** [comment]
Any resolution on this? I would set the floor at the [SSE 4.2 instruction set](https://en.wikipedia.org/wiki/SSE4#SSE4.2) introduced in 2008 with the Nehalem architecture, because of the string matching instructions. Klaus Post has made good use of them in his [Golang DEFLATE implementation](https://github.com/klauspost/compress/), for example. Libdeflate might use them too – I know he uses AVX, which is a few generations newer.

Kazuho Oku also uses SSE 4.2 in his [PicoHTTPParser](https://github.com/h2o/picohttpparser).

Or you could set the floor at Intel's 2010 [Westmere generation](https://en.wikipedia.org/wiki/Westmere_(microarchitecture)) (and AMD's Jaguar), which adds the [carryless multiplication](https://en.wikipedia.org/wiki/CLMUL_instruction_set) instruction, which is very handy for CRC work.

I imagine that zlib-ng's main use case is for servers (though I'm still not clear on whether it's supposed to work with nginx right now). Server environments should have no problem with a Westmere minimum. That's before Sandy Bridge and very old by server standards. (It probably costs a lot more in electric bills to run the same workloads on a pre-Westmere server compared to a Haswell, Broadwell, or Skylake.)

**Comment by mtl1979** [comment]
I started on the code long time ago, but hit some compiler issues that I couldn't resolve... I also have no machine that supports SSE4.2 or later instruction sets so I couldn't debug all variants locally so I did have to rely on Travis CI for verification.

**Comment by JoeUX** [comment]
I might be able to ship you an Ivy Bridge laptop in a month or two. I'll follow up when I know for sure.

**Comment by nmoinvaz** [comment]
I think this work has been complete now with #588.
