### ISSUE TITLE
riscv64 support in cmake is broken

### ISSUE THREAD

**Issue by Civil** [zlib-ng/zlib-ng#941]
Currently if architecture is not detected it falls back to x86, with SSE2 and other stuff enabled, which is incorrect for riscv64.

I'm not sure what would be the best course of actions here - either to fallback to generic or add riscv64 (or maybe both) though as I don't know what were intentions behind fallback to x86.

**Comment by mtl1979** [comment]
"generic" architecture used to be same code path as 80x86 (32-bit, little-endian, Linux)... It was never changed as all other combinations and choices were subsequently added as soon as optimized versions were added. As already mentioned elsewhere, we combined code paths for 32-bit and 64-bit processors when the instruction sets clearly overlapped.

We haven't decided yet if we should separate "generic" and "x86" cases to eliminate unnecessary checking and/or enabling of SSE2 or other x86 specific instruction sets.

**Comment by Civil** [comment]
What I meant that behavior of `configure` and cmake build systems are fundamentally different here. In case of `configure` if it fails to detect architecture it falls back to generic.

In case of cmake it's clearly falls back to x86 in that case.

I've changed the PR to define just `riscv`.

**Comment by mtl1979** [comment]
Yes... configure has more fine-grained detection... cmake support was quite unfinished when zlib-ng was forked from zlib and since that it has evolved more than the configure script... We still support using configure (and other alternatives, like nmake) as configure script has always been more advanced and cmake isn't installed by default on a lot of systems.
