### ISSUE TITLE
Relationship between this project and "pigz" parallel compression?

### ISSUE THREAD

**Issue by vielmetti** [zlib-ng/zlib-ng#96]
Hi, I have used pigz from https://github.com/madler/pigz with some good success on a manycore Packet 2A (96 core ARMv8) machine. It parallelizes compression by breaking a file into chunks and running each chunk on a separate thread.

There are a couple of hints in the readmes about pigz, but I'm wondering two things

* are you regularly testing against this implementation
* are there further performance speedups to be had by parallelization

**Comment by Dead2** [comment]
Yes there is a potential for speedups by parallelization,since zlib/zlib-ng only utilizes a single thread to do the compression. So pigz should in theory give the same speedup ratio with zlib-ng as it does with zlib.

However I have not done any testing with pigz myself, and I have not heard of anyone else that has tested it with zlib-ng yet.

It would probably be a good thing to start testing against though.
